# ___Themeda triandra - Power Analysis___
------------------

In [2]:
!python --version

Python 3.13.9

The system cannot find the path specified.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.api as sm

from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from numba import njit

In [18]:
# load in the data for soil and climatic properties and root trait data
root_traits = pd.read_csv(r"../data/chapter3/vin_themeda_root_traits.csv", usecols=("Accession", "SRL", "RTD", "Diameter")) # units => m/g, g/cm3, mm
root_traits = root_traits.rename({_: _.lower().strip() for _ in root_traits.columns}, axis=1)
root_traits.loc[:, "accession"] = root_traits.accession.replace({_:_.replace(' ', '_').strip() for _ in root_traits.accession.unique()})
root_traits.head()

           accession        srl       rtd  diameter
0          Dalby_QLD  16.292527  0.256367    0.5521
1          Dalby_QLD  35.587354  0.145137    0.4965
2          Dalby_QLD  26.271140  0.332818    0.3816
3          Dalby_QLD  17.405689  0.176030    0.6447
4  Mt_Fox_N_Park_QLD  35.094561  0.265127    0.3699

In [20]:
root_traits.accession.unique()

array(['Dalby_QLD', 'Mt_Fox_N_Park_QLD', 'Panawonica_WA',
       'Rainbow_Valley_NT', 'Sydney', 'Virginia_Gardens_SA'], dtype=object)

In [24]:
pd.read_csv(r"../data/chapter3/site_metereology.csv", skiprows=range(2), usecols=("site", "state", "annual_rainfall_mm", "mean_annual_temp_celsius"))

                   site state  annual_rainfall_mm  mean_annual_temp_celsius
0        Rainbow Valley    NT               189.3                      28.9
1            Panawonica    WA               404.4                      34.7
2                Forbes   NSW               520.4                      24.5
3                Hobart   TAS               611.4                      17.0
4                 Dalby   QLD               621.4                      27.0
5      Virginia Gardens    SA               468.7                      22.6
6  Mt Fox National Park   QLD               642.8                      29.3
7                Sydney   NSW              1156.9                      23.4