In [2]:
!python --version

Python 3.13.9

The system cannot find the path specified.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
subset = pd.read_csv("../../data/chapter2/FREDv3subset/FRED_subset.csv")
subset.insert(loc=0, column="binominal", value=subset.F01286 + ' ' + subset.F01287)

In [7]:
subset

,binominal,F00679,F00727,F00261,F00709,F00043,F00056,F00645,F00004,F01286,F01287,F01289,F01290
0,Populus trichocarpa,0.142951,447.167648,18.478265,0.169294,C3,1.0,NaN,"Hajek P, Hertel D, Leuschner C. 2014. Root ord...",Populus,trichocarpa,Salicaceae,Malpighiales
1,Populus trichocarpa,0.249630,166.388374,14.456530,0.160036,C3,2.0,NaN,"Hajek P, Hertel D, Leuschner C. 2014. Root ord...",Populus,trichocarpa,Salicaceae,Malpighiales
2,Populus trichocarpa,0.425085,60.723679,10.760881,0.171351,C3,3.0,NaN,"Hajek P, Hertel D, Leuschner C. 2014. Root ord...",Populus,trichocarpa,Salicaceae,Malpighiales
3,Populus tremula,0.175513,330.424588,22.065220,0.169294,C3,1.0,NaN,"Hajek P, Hertel D, Leuschner C. 2014. Root ord...",Populus,tremula,Salicaceae,Malpighiales
4,Populus tremula,0.285828,116.664475,16.304355,0.160041,C3,2.0,NaN,"Hajek P, Hertel D, Leuschner C. 2014. Root ord...",Populus,tremula,Salicaceae,Malpighiales
...,...,...,...,...,...,...,...,...,...,...,...,...,...
598,Prunus sargentii,0.042154,81.443333,19.366667,0.103333,C3,1.0,NaN,Valverde et al (unpublished),Prunus,sargentii,Rosaceae,Rosales
599,Sassafras albidum,0.219538,20.513333,23.200000,0.116667,C3,1.0,NaN,Valverde et al (unpublished),Sassafras,albidum,Lauraceae,Laurales
600,Styphnolobium japonicum,0.086988,36.817500,26.300000,0.155000,C3,1.0,NaN,Valverde et al (unpublished),Styphnolobium,japonicum,Fabaceae,Fabales
601,Syringa reticulata,0.061422,89.920000,23.900000,0.075000,C3,1.0,NaN,Valverde et al (unpublished),Syringa,reticulata,Oleaceae,Lamiales
602,Ulmus americana,0.076581,71.770000,16.325000,0.077500,C3,1.0,NaN,Valverde et al (unpublished),Ulmus,americana,Ulmaceae,Rosales

In [29]:
# RTD (709) from the conservation axis & SRL (727) from the collaboration axis
subset.loc[:, ["binominal", "F00727", "F00709"]].groupby("binominal", as_index=True).mean()

                            F00727    F00709
binominal
Acacia auriculiformis    53.822500  0.270000
Acacia crassicarpa      108.280000  0.360000
Acacia mangium           99.190000  0.290000
Acer davidii             69.587172  0.323158
Acer fabri               67.160000  0.530000
...                            ...       ...
Ulmus americana          46.487909  0.158625
Ulmus davidiana          45.293761  0.388925
Ulmus macrocarpa         50.289323  0.353696
Vaccinium mandarinorum  106.710000  0.530000
Wendlandia uvariifolia   45.270000  0.430000

[203 rows x 2 columns]

In [30]:
subset.loc[:, ["binominal", "F00727", "F00709"]].groupby("binominal", as_index=True).mean().to_csv(r"../../data/chapter2/FREDv3subset/RTD_SRL_species_means.csv", index=True)