# ___Taxonomic coverage and mycorrhizal state distribution in FRED 4.0 subset___
----------------------------------------------

In [1]:
!python --version

Python 3.14.6

The system cannot find the path specified.

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
#-----------------
# info from APG4
#-----------------


APG4_GYMNOSPERMS = ("Cycadaceae", "Zamiaceae", "Ginkgoaceae", "Ephedraceae", "Welwitschiaceae", "Gnetaceae", "Pinaceae", "Araucariaceae", "Podocarpaceae", "Sciadopityaceae", "Taxaceae", "Cupressaceae")

# ferns
APG4_MONILOPHYTES = ("Equisetaceae", "Ophioglossaceae", "Psilotaceae", "Marattiaceae", "Osmundaceae", "Hymenophyllaceae", "Gleicheniaceae", "Matoniaceae", "Dipteridaceae", "Anemiaceae", "Lygodiaceae", "Schizaeaceae", "Marsileaceae", "Salviniaceae", "Cyatheaceae", "Cibotiaceae", "Dicksoniaceae", "Metaxyaceae", "Thyrsopteridaceae", "Loxsomataceae", "Culcitaceae", "Plagiogyriaceae",
                     "Saccolomataceae", "Cystodiaceae", "Lonchitidaceae", "Lindsaeaceae", "Pteridaceae", "Dennstaedtiaceae", "Polypodiaceae", "Davalliaceae", "Didymochlaenaceae", "Dryopteridaceae", "Hypodematiaceae", "Lomariopsidaceae", "Oleandraceae", "Tectariaceae", "Aspleniaceae", "Athyriaceae", "Blechnaceae", "Cystopteridaceae", "Desmophlebiaceae", "Diplaziopsidaceae", "Hemidictyaceae",
                     "Onocleaceae", "Rhachidosoraceae", "Thelypteridaceae", "Woodsiaceae")

# bryophytes
APG4_BRYOPHYTES = ("Treubiaceae", "Haplomitriaceae", "Blasiaceae", "Neohodgsoniaceae", "Riellaceae", "Sphaerocarpaceae", "Aytoniaceae", "Cleveaceae", "Conocephalaceae", "Cyathodiaceae", "Dumortieraceae", "Exormothecaceae", "Lunulariaceae", "Marchantiaceae", "Monosoleniaceae", "Targioniaceae", "Ricciaceae", "Oxymitraceae", "Noterocladaceae", "Pelliaceae", "Fossombroniaceae", "Petalophyllaceae", "Pallavicinaceae",
                   "Pleuroziaceae", "Aneuraceae", "Metzgeriaceae", "Ptilidiaceae", "Jubulaceae", "Frullaniaceae", "Lejeuneaceae", "Lepidolaenaceae", "Porellaceae", "Radulaceae", "Acrobolbaceae", "Balantiopsaceae", "Calypogeiaceae", "Cephaloziaceae", "Cephaloziellaceae", "Geocalycaceae", "Gymnomitriaceae", "Jungermanniaceae", "Lepidoziaceae", "Lophoziaceae", "Scapaniaceae", "Trichocoleaceae", "Sphagnaceae", "Flatbergiaceae",
                   "Ambuchananiaceae", "Takakiaceae", "Andreaeaceae", "Andreaeobryaceae", "Tetraphidaceae", "Oedipodiaceae", "Polytrichaceae", "Buxbaumiaceae", "Diphysciaceae", "Gigaspermaceae", "Disceliaceae", "Encalyptaceae", "Funariaceae", "Timmiaceae", "Bruchiaceae", "Calymperaceae", "Catoscopiaceae", "Dicranaceae", "Ditrichaceae", "Fissidentaceae", "Leucobryaceae", "Rhabdoweisiaceae", "Pottiaceae", "Ephemeraceae", "Grimmiaceae",
                   "Seligeriaceae", "Hedwigiaceae", "Helicophyllaceae", "Rhacocarpaceae", "Bartramiaceae", "Meesiaceae", "Splachnaceae", "Bryaceae", "Mniaceae", "Plagiomniaceae", "Orthotrichaceae", "Orthodontiaceae", "Calomniaceae", "Cyrtopodaceae", "Mitteniaceae", "Rhizogoniaceae", "Spiridentaceae", "Aulacomniaceae", "Braithwaiteaceae", "Hypnodendraceae", "Pterobryellaceae", "Racopilaceae", "Garovagliaceae", "Ptychomniaceae", "Daltoniaceae",
                   "Hookeriaceae", "Hypopterygiaceae", "Leucomiaceae", "Pilotrichaceae", "Saulomataceae", "Schimperobryaceae", "Amblystegiaceae", "Anomodontaceae", "Brachytheciaceae", "Calliergonaceae", "Campyliaceae", "Cryphaeaceae", "Hypnaceae", "Hylocomiaceae", "Hypopterygiaceae", "Lembophyllaceae", "Leskeaceae", "Meteoriaceae", "Miyabeaceae", "Neckeraceae", "Plagiotheciaceae", "Pterobryaceae", "Pylaisiadelphaceae", "Sematophyllaceae",
                   "Thuidiaceae", "Trachylomaceae", "Leiosporocerotaceae", "Anthocerotaceae", "Foliocerotaceae", "Notothyladaceae", "Phymatocerotaceae", "Dendrocerotaceae")

# lycophytes
APG4_LYCOPHYTES = ("Lycopodiaceae", "Isoetaceae", "Selaginellaceae")

In [4]:
apg4_angiosperms = pd.read_csv(r"../../../APG4/apg4.txt", sep='\t', usecols=["scientificName", "taxonRank", "parentNameUsage"]) # this will save us a ton of time
apg4_angiosperms # this does not have data for gymnosperms!!!!!

      scientificName taxonRank parentNameUsage
0            Plantae   kingdom             NaN
1        angiosperms     clade         Plantae
2       Amborellales     order     angiosperms
3      Amborellaceae    family    Amborellales
4        Nymphaeales     order     angiosperms
..               ...       ...             ...
519   Griseliniaceae    family         Apiales
520   Myodocarpaceae    family         Apiales
521    Pennantiaceae    family         Apiales
522   Pittosporaceae    family         Apiales
523  Torricelliaceae    family         Apiales

[524 rows x 3 columns]

In [8]:
data = pd.read_excel(r"../../data/chapter2/FRED/subsets/final.xlsx", sheet_name="final", usecols=["binominal", "F01286", "F01289", "state"]) # this is the dataset where the binominal names and their higher classifications have been reconciled with the phylogeny
data

                  binominal         F01286          F01289  state
0                Abies alba          Abies        Pinaceae    EcM
1         Abies nephrolepis          Abies        Pinaceae    EcM
2     Acacia auriculiformis         Acacia        Fabaceae  EcMAM
3        Acacia crassicarpa         Acacia        Fabaceae  EcMAM
4            Acacia mangium         Acacia        Fabaceae  EcMAM
...                     ...            ...             ...    ...
1296    Xanthophyllum tenue  Xanthophyllum    Polygalaceae     AM
1297        Zabelia biflora        Zabelia  Caprifoliaceae     AM
1298         Zamia lucayana          Zamia       Zamiaceae     AM
1299            Zizia aurea          Zizia        Apiaceae     AM
1300       Zygia inaequalis          Zygia        Fabaceae     AM

[1301 rows x 4 columns]

In [53]:
apg4_angiosperms.taxonRank.unique()

<StringArray>
['kingdom', 'clade', 'order', 'family']
Length: 4, dtype: str

In [54]:
apg4_angiosperms.query(r"taxonRank=='family'")

        scientificName taxonRank   parentNameUsage
3        Amborellaceae    family      Amborellales
5          Cabombaceae    family       Nymphaeales
6        Hydatellaceae    family       Nymphaeales
7         Nymphaeaceae    family       Nymphaeales
9    Austrobaileyaceae    family  Austrobaileyales
..                 ...       ...               ...
519     Griseliniaceae    family           Apiales
520     Myodocarpaceae    family           Apiales
521      Pennantiaceae    family           Apiales
522     Pittosporaceae    family           Apiales
523    Torricelliaceae    family           Apiales

[446 rows x 3 columns]

In [55]:
apg4_angiosperms.query(r"taxonRank=='order'")

       scientificName taxonRank parentNameUsage
2        Amborellales     order     angiosperms
4         Nymphaeales     order     angiosperms
8    Austrobaileyales     order     angiosperms
13         Canellales     order      magnoliids
16          Piperales     order      magnoliids
..                ...       ...             ...
505     Escalloniales     order     campanulids
507         Bruniales     order     campanulids
510    Paracryphiales     order     campanulids
512        Dipsacales     order     campanulids
515           Apiales     order     campanulids

[64 rows x 3 columns]

In [5]:
apg4_angiosperms = pd.merge(left=apg4_angiosperms.query(r"taxonRank=='family'"), left_on="parentNameUsage", # family - order pairs
         right=apg4_angiosperms.query(r"taxonRank=='order'"), right_on="scientificName", # order - higher taxon pairs
         how="left", suffixes=('', "_")).drop(["scientificName_", "taxonRank", "taxonRank_"], axis=1).rename({"scientificName": "family", "parentNameUsage": "order", "parentNameUsage_": "group"}, axis=1)
apg4_angiosperms

                family             order        group
0        Amborellaceae      Amborellales  angiosperms
1          Cabombaceae       Nymphaeales  angiosperms
2        Hydatellaceae       Nymphaeales  angiosperms
3         Nymphaeaceae       Nymphaeales  angiosperms
4    Austrobaileyaceae  Austrobaileyales  angiosperms
..                 ...               ...          ...
441     Griseliniaceae           Apiales  campanulids
442     Myodocarpaceae           Apiales  campanulids
443      Pennantiaceae           Apiales  campanulids
444     Pittosporaceae           Apiales  campanulids
445    Torricelliaceae           Apiales  campanulids

[446 rows x 3 columns]

In [7]:
apg4_angiosperms.to_csv(r"../../data/chapter2/APG4_angiosperms_taxonomy.csv", index=False)

In [70]:
# all the angiosperms in the subset
pd.merge(left=data, left_on="F01289", right=apg4_angiosperms, right_on="family", how="inner")

,binominal,F01286,F01289,state,family,order,group
0,Acacia auriculiformis,Acacia,Fabaceae,EcMAM,Fabaceae,Fabales,fabids
1,Acacia crassicarpa,Acacia,Fabaceae,EcMAM,Fabaceae,Fabales,fabids
2,Acacia mangium,Acacia,Fabaceae,EcMAM,Fabaceae,Fabales,fabids
3,Acer barbinerve,Acer,Sapindaceae,AM,Sapindaceae,Sapindales,malvids
4,Acer campbellii,Acer,Sapindaceae,AM,Sapindaceae,Sapindales,malvids
...,...,...,...,...,...,...,...
1178,Xanthophyllum flavescens,Xanthophyllum,Polygalaceae,AM,Polygalaceae,Fabales,fabids
1179,Xanthophyllum tenue,Xanthophyllum,Polygalaceae,AM,Polygalaceae,Fabales,fabids
1180,Zabelia biflora,Zabelia,Caprifoliaceae,AM,Caprifoliaceae,Dipsacales,campanulids
1181,Zizia aurea,Zizia,Apiaceae,AM,Apiaceae,Apiales,campanulids
1182,Zygia inaequalis,Zygia,Fabaceae,AM,Fabaceae,Fabales,fabids

In [77]:
data.state.value_counts()

state
AM       1098
EcM       120
NMAM       38
EcMAM      20
NM         16
ErM         9
Name: count, dtype: int64

In [76]:
pd.merge(left=data, left_on="F01289", right=apg4_angiosperms, right_on="family", how="inner").groupby("group", as_index=True).agg({"state": "value_counts"})

                     state
group         state
angiosperms   AM         5
asterids      AM        71
              ErM        9
              NMAM       1
              EcM        1
campanulids   AM       128
eudicots      AM         9
              NM         9
              NMAM       1
fabids        AM       185
              EcM       70
              EcMAM      3
              NMAM       3
              NM         1
lamiids       AM       118
              NMAM       3
              NM         1
magnoliids    AM       138
              NMAM       2
malvids       AM       187
              EcM       22
              EcMAM      5
              NM         5
monocots      AM        71
              NMAM      15
rosids        AM        83
              EcMAM     12
superasterids NMAM       7
              AM         3
              EcM        2
superrosids   AM        10
              NMAM       3

In [81]:
data.query(r"state=='NM'")

                 binominal       F01286         F01289 state
150        Berteroa incana     Berteroa   Brassicaceae    NM
355     Descurainia sophia  Descurainia   Brassicaceae    NM
369         Draba nemorosa        Draba   Brassicaceae    NM
415  Erysimum inconspicuum     Erysimum   Brassicaceae    NM
511     Hakea ceratophylla        Hakea     Proteaceae    NM
512       Hakea cyclocarpa        Hakea     Proteaceae    NM
513         Hakea linearis        Hakea     Proteaceae    NM
514      Hakea lissocarpha        Hakea     Proteaceae    NM
515       Hakea oldfieldii        Hakea     Proteaceae    NM
516      Hakea tuberculata        Hakea     Proteaceae    NM
517            Hakea varia        Hakea     Proteaceae    NM
562      Helicia formosana      Helicia     Proteaceae    NM
633       Knightia excelsa     Knightia     Proteaceae    NM
655   Lepidium densiflorum     Lepidium   Brassicaceae    NM
725       Lupinus perennis      Lupinus       Fabaceae    NM
895     Orthocarpus luteus  Orthocarpus  Orobanchaceae    NM

In [58]:
data.query(r"F01289.isin(@APG4_GYMNOSPERMS)") # gymnosperms

                  binominal      F01286         F01289 state
0                Abies alba       Abies       Pinaceae   EcM
1         Abies nephrolepis       Abies       Pinaceae   EcM
35      Afrocarpus falcatus  Afrocarpus  Podocarpaceae    AM
37        Agathis australis     Agathis  Araucariaceae    AM
38    Agathis kinabaluensis     Agathis  Araucariaceae    AM
...                     ...         ...            ...   ...
1227     Thuja occidentalis       Thuja   Cupressaceae    AM
1239    Torreya californica     Torreya       Taxaceae    AM
1240       Torreya nucifera     Torreya       Taxaceae    AM
1255       Tsuga canadensis       Tsuga       Pinaceae   EcM
1298         Zamia lucayana       Zamia      Zamiaceae    AM

[82 rows x 4 columns]

In [79]:
data.query(r"F01289.isin(@APG4_GYMNOSPERMS)").state.value_counts()

state
AM     57
EcM    25
Name: count, dtype: int64

In [75]:
data.query(r"F01289.isin(@APG4_GYMNOSPERMS)").groupby("F01289", as_index=True).agg({"state": "value_counts"})

                       state
F01289          state
Araucariaceae   AM         5
Cupressaceae    AM        16
Cycadaceae      AM         2
Ephedraceae     AM         2
Ginkgoaceae     AM         1
Gnetaceae       AM         1
Pinaceae        EcM       25
Podocarpaceae   AM        22
Sciadopityaceae AM         1
Taxaceae        AM         4
Zamiaceae       AM         3

In [64]:
data.query(r"F01289.isin(@APG4_BRYOPHYTES)") # bryophytes

Empty DataFrame
Columns: [binominal, F01286, F01289, state]
Index: []

In [60]:
data.query(r"F01289.isin(@APG4_MONILOPHYTES)") # ferns

                      binominal         F01286            F01289 state
30             Adiantum pedatum       Adiantum       Pteridaceae    AM
67            Alsophila smithii      Alsophila       Cyatheaceae    AM
68           Alsophila tricolor      Alsophila       Cyatheaceae    AM
124        Asplenium bulbiferum      Asplenium      Aspleniaceae  NMAM
137         Athyrium monomachii       Athyrium       Athyriaceae    AM
138            Athyrium sinense       Athyrium       Athyriaceae    AM
139         Athyrium spinulosum       Athyrium       Athyriaceae    AM
160           Blechnum discolor       Blechnum      Aspleniaceae    AM
161        Blechnum fluviatilis       Blechnum      Aspleniaceae    AM
162        Blechnum lanceolatum       Blechnum      Aspleniaceae    AM
163    Blechnum novae-zelandiae       Blechnum      Aspleniaceae    AM
164          Blechnum orientale       Blechnum      Aspleniaceae    AM
165           Blechnum procerum       Blechnum      Aspleniaceae    AM
260           Cibotium barometz       Cibotium       Cibotiaceae    AM
334             Cyathea smithii        Cyathea       Cyatheaceae    AM
338        Cystopteris sudetica    Cystopteris  Cystopteridaceae    AM
359         Dicksonia squarrosa      Dicksonia     Dicksoniaceae    AM
360      Dicranopteris linearis  Dicranopteris    Gleicheniaceae    AM
361        Dicranopteris pedata  Dicranopteris    Gleicheniaceae    AM
372       Dryopteris lepidopoda     Dryopteris   Dryopteridaceae    AM
373           Dryopteris sparsa     Dryopteris   Dryopteridaceae    AM
404           Equisetum hyemale      Equisetum      Equisetaceae  NMAM
405          Equisetum pratense      Equisetum      Equisetaceae  NMAM
774   Matteuccia struthiopteris     Matteuccia       Onocleaceae    AM
891          Onoclea sensibilis        Onoclea       Onocleaceae    AM
897            Osmunda japonica        Osmunda       Osmundaceae    AM
990        Polystichum chilense    Polystichum   Dryopteridaceae    AM
1059        Pteridium aquilinum      Pteridium  Dennstaedtiaceae    AM
1174   Sphaeropteris medullaris  Sphaeropteris       Cyatheaceae    AM
1183     Sticherus cunninghamii      Sticherus    Gleicheniaceae    AM

In [80]:
data.query(r"F01289.isin(@APG4_MONILOPHYTES)").state.value_counts()

state
AM      27
NMAM     3
Name: count, dtype: int64

In [74]:
data.query(r"F01289.isin(@APG4_MONILOPHYTES)").groupby("F01289", as_index=True).agg({"state": "value_counts"})

                        state
F01289           state
Aspleniaceae     AM         6
                 NMAM       1
Athyriaceae      AM         3
Cibotiaceae      AM         1
Cyatheaceae      AM         4
Cystopteridaceae AM         1
Dennstaedtiaceae AM         1
Dicksoniaceae    AM         1
Dryopteridaceae  AM         3
Equisetaceae     NMAM       2
Gleicheniaceae   AM         3
Onocleaceae      AM         2
Osmundaceae      AM         1
Pteridaceae      AM         1

In [63]:
data.query(r"F01289.isin(@APG4_LYCOPHYTES)") # lycophytes

               binominal      F01286         F01289 state
726  Lycopodium volubile  Lycopodium  Lycopodiaceae    AM

In [29]:
data.binominal.unique().size # species we have traits and states for in the subset

1301

In [24]:
all_apg4_fams = APG4_BRYOPHYTES + APG4_LYCOPHYTES + APG4_MONILOPHYTES + APG4_GYMNOSPERMS + tuple(apg4_angiosperms.family.values)

In [30]:
data.query(r"not F01289.isin(@all_apg4_fams)") # of the 1301 species, these aren't covered by the APG4 docs (pds and the angiosperm dataset)

                      binominal        F01286           F01289 state
240   Cephalotaxus harringtonii  Cephalotaxus  Cephalotaxaceae    AM
1125        Sambucus williamsii      Sambucus      Viburnaceae    AM
1275          Viburnum dentatum      Viburnum      Viburnaceae    AM
1276        Viburnum stipitatum      Viburnum      Viburnaceae    AM
1277             Viburnum tinus      Viburnum      Viburnaceae    AM

In [36]:
# according to APG4 Cephalotaxus harringtonii belongs to family Taxaceae (a gymnosperm)

In [39]:
# Adoxaceae is a synonym for Viburnaceae
# https://en.wikipedia.org/wiki/Adoxaceae

apg4_angiosperms.query(r"family=='Adoxaceae'")

        family       order        group
436  Adoxaceae  Dipsacales  campanulids

In [41]:
data.state.value_counts()

state
AM       1098
EcM       120
NMAM       38
EcMAM      20
NM         16
ErM         9
Name: count, dtype: int64