In [3]:
print(R.version$version.string)

[1] "R version 4.6.1 (2026-06-24 ucrt)"

In [74]:
suppressPackageStartupMessages({
    library("ape")
    library("phytools")
    library("corHMM")
    library("OUwie")
    library("readxl")
    library("ggplot2")
})
source("../houwie_patches.R") # this contains patched versions of OUwie::getModelTable and OUwie::getModelAvgParams

read_all_rds <- function(dirpath, cd, strip, rm_underscores = TRUE) {
    # dirpath = path to the directory containing the .Rds files
    # cd = character dependent or independent models, these are expected to contain "CD" or "CID" in their names
    # strip = the regex pattern to strip out of the file names when naming objects, can be a plain string as well
    # rm_underscores - strip all the underscores in the object name

    fnames <- list.files(dirpath) # all the files in the specified dir
    if(cd) fnames <- fnames[grep(pattern = "CD", fnames)]
    else fnames <- fnames[grep(pattern = "CID", fnames)] # cherry pick CD or CID models, given their names contain "CD" or "CID" to distinguish them
    # print(fnames)

    paths <- paste0(dirpath, fnames) # relative paths for all the Rds files
    stopifnot(length(fnames)==length(paths))

    # remove the unnecessary parts of the file names to create the model names and also remove all the underscores
    mnames <- fnames |> gsub(pattern = ".Rds", replacement = '') |> gsub(pattern = strip, replacement = '') |> gsub(pattern = ifelse(rm_underscores, '_', ''), replacement = '')
    stopifnot(length(fnames)==length(mnames))
    stopifnot(length(paths)==length(mnames))

    models <- list()
    for (i in seq_along(mnames)) models[[mnames[i]]] <- readRDS(file = paths[i])
    stopifnot(length(models)==length(mnames))

    models
}

In [13]:
packageVersion("OUwie")

[1] '3.0.3'

In [14]:
packageVersion("corHMM")

[1] '2.8'

In [42]:
fred4 <- read.csv("../../data/chapter2/FRED/subsets/continuous_raw.csv")
s <- readxl::read_xlsx("../../data/chapter2/FRED/subsets/final.xlsx", sheet = "final")[c("binominal", "state")]
s$binominal <- gsub(s$binominal, pattern = ' ', replacement = '_')
fred4 <- merge(fred4, s, by = "binominal", all.x = TRUE)

# ___Hypotheses___

- Evolution of mycorrhizal states and fine root ecological strategies will be correlated. We expect that the RD, SRL and RTD will show correlated evolution with mycorrhizal states (__overall character dependency - if found show what OU parameters show character dependency__).
  
- Evolutionary rates of the fine root traits $\sigma^2$ would be higher when they are paired to a hybrid (dual) mycorrhizal state (e.g. AM/NM, AM/EcM) than a singular mycorrhizal state (e.g. AM, EcM). 
  
- Evolutionary rate $\sigma^2$ of fine root traits should be the lowest when paired to NM.

__Can also add the pull towards the optima $\theta$ - $\alpha$ to the last two hypotheses.__

In [19]:
# these models were all fit with 250 simmaps, a phylogeny of 1301 plant species including ErM states
# these models were fit using the following template

```R
OUwie::hOUwie(phy = phylogeny,
              data = data,
              rate.cat = {2 if null_model else 1},
              discrete_model = discrete_model,
              continuous_model = continuous_model,
              nSim = 250,
              null.model = {TRUE if null_model else FALSE},
              lb_discrete_model = lb_discrete_model, # 1e-15
              ub_discrete_model = ub_discrete_model, # 10.000
              lb_continuous_model = c(lb_continuous_model.alpha, lb_continuous_model.sigma_sq, lb_continuous_model.theta), # these were set to defaults
              ub_continuous_model = c(ub_continuous_model.alpha, ub_continuous_model.sigma_sq, ub_continuous_model.theta) # these were set to defaults
)
```

In [16]:
rd_cd <- read_all_rds(dirpath = "../../data/chapter2/rdata/parallel/hie-general3/F00679/", cd = TRUE, strip = "_F00679_CD_250")
rd_cid <- read_all_rds(dirpath = "../../data/chapter2/rdata/parallel/hie-general3/F00679/", cd = FALSE, strip = "_F00679_CID_250")

In [24]:
merge(OUwie::getModelTable(rd_cd, type = "AICc")[c("AICc", "dAICc")],
      OUwie::getModelTable(rd_cid, type = "AICc")[c("AICc", "dAICc")],
      by = 0, all = TRUE, suffixes = c("_CD", "_CID"))

   Row.names AICc_CD    dAICc_CD    AICc_CID  dAICc_CID
1  ARDOUM     156566.78  129654.769 221312.34 208582.4252
2  ARDOUMA    225011.14  198099.123  46352.32  33622.4039
3  ARDOUMV   1021122.13  994210.116 241934.92 229204.9964
4  ARDOUMVA  4797144.25 4770232.240  12729.92      0.0000
5  EROUM      392226.26  365314.252 721766.58 709036.6637
6  EROUMA     600719.97  573807.953  18741.80   6011.8794
7  EROUMV     157222.52  130310.511 346898.80 334168.8801
8  EROUMVA     39762.09   12850.079  13224.63    494.7128
9  SYMOUM     296939.01  270026.993 346720.21 333990.2903
10 SYMOUMA     26912.01       0.000 147610.21 134880.2908
11 SYMOUMV    492226.63  465314.616  47931.81  35201.8924
12 SYMOUMVA    34622.63    7710.616 145401.34 132671.4203

In [27]:
# issue with the current implementation - comes from getModelTable() line 739 - error check for number of models should go before the row mismatch error check
# in call to getModelTable inside getModelAvgParams at line 787 (after dropping the failed? models)
rd_cd_avgs <- OUwie::getModelAvgParams(rd_cd, type = "AICc", force = FALSE)

ERROR: Error in if (var(unlist(lapply(model.list, function(x) dim(x$data)[1]))) != : missing value where TRUE/FALSE needed

In [28]:
rd_cd_avgs <- getModelAvgParams_patched(rd_cd, type = "AICc", force = FALSE)

In [29]:
rd_cd_avgs

                          rates       alpha        sigma.sq  theta
Ratibida_pinnata          0.001396594 3.188131e-02 0.1729462 -0.8745306
Heliopsis_helianthoides   0.001396594 3.188131e-02 0.1729462 -0.8745306
Liatris_aspera            0.001396594 3.188131e-02 0.1729462 -0.8745306
Arnica_sororia            0.001396594 3.188131e-02 0.1729462 -0.8745306
Arnica_fulgens            0.001396594 3.188131e-02 0.1729462 -0.8745306
Hymenoxys_richardsonii    0.001396594 3.188131e-02 0.1729462 -0.8745306
Helianthus_agrestis       0.001396594 3.188131e-02 0.1729462 -0.8745306
Helianthus_grosseserratus 0.001396594 3.188131e-02 0.1729462 -0.8745306
Helianthus_giganteus      0.001396594 3.188131e-02 0.1729462 -0.8745306
Helianthus_maximiliani    0.001396594 3.188131e-02 0.1729462 -0.8745306
Helianthus_verticillatus  0.001396594 3.188131e-02 0.1729462 -0.8745306
Helianthus_salicifolius   0.001396594 3.188131e-02 0.1729462 -0.8745306
Pappobolus_microphyllus   0.001396594 3.188131e-02 0.1729462 -0.8745306
Helianthus_occidentalis   0.001396594 3.188131e-02 0.1729462 -0.8745306
Helianthus_mollis         0.001396594 3.188131e-02 0.1729462 -0.8745306
Helianthus_silphioides    0.001396594 3.188131e-02 0.1729462 -0.8745306
Helianthus_atrorubens     0.001396594 3.188131e-02 0.1729462 -0.8745306
Helianthus_longifolius    0.001114209 2.306275e-05 0.1729462 -1.1610522
Helianthus_angustifolius  0.001396594 3.188131e-02 0.1729462 -0.8745306
Helianthus_floridanus     0.001396594 3.188131e-02 0.1729462 -0.8745306
Helianthus_petiolaris     0.001396594 3.188131e-02 0.1729462 -0.8745306
Helianthus_neglectus      0.001396594 3.188131e-02 0.1729462 -0.8745306
Helianthus_niveus         0.001396594 3.188131e-02 0.1729462 -0.8745306
Helianthus_praecox        0.001396594 3.188131e-02 0.1729462 -0.8745306
Helianthus_debilis        0.001396594 3.188131e-02 0.1729462 -0.8745306
Helianthus_argophyllus    0.001396594 3.188131e-02 0.1729462 -0.8745306
Helianthus_annuus         0.001396594 3.188131e-02 0.1729462 -0.8745306
Helianthus_cusickii       0.001396594 3.188131e-02 0.1729462 -0.8745306
Helianthus_pauciflorus    0.001396594 3.188131e-02 0.1729462 -0.8745306
Helianthus_radula         0.001396594 3.188131e-02 0.1729462 -0.8745306
⋮                         ⋮           ⋮            ⋮         ⋮
Dryopteris_lepidopoda     0.001396594 3.188131e-02 0.1729462 -0.8745306
Polystichum_chilense      0.001396594 3.188131e-02 0.1729462 -0.8745306
Blechnum_procerum         0.001396594 3.188131e-02 0.1729462 -0.8745306
Blechnum_novae-zelandiae  0.001396594 3.188131e-02 0.1729462 -0.8745306
Blechnum_lanceolatum      0.001396594 3.188131e-02 0.1729462 -0.8745306
Blechnum_fluviatilis      0.001396594 3.188131e-02 0.1729462 -0.8745306
Blechnum_discolor         0.001396594 3.188131e-02 0.1729462 -0.8745306
Blechnum_orientale        0.001396594 3.188131e-02 0.1729462 -0.8745306
Onoclea_sensibilis        0.001114209 2.306275e-05 0.1729462 -1.1610522
Matteuccia_struthiopteris 0.001114209 2.306275e-05 0.1729462 -1.1610522
Athyrium_spinulosum       0.001396594 3.188131e-02 0.1729462 -0.8745306
Athyrium_sinense          0.001396594 3.188131e-02 0.1729462 -0.8745306
Athyrium_monomachii       0.001396594 3.188131e-02 0.1729462 -0.8745306
Cystopteris_sudetica      0.001396594 3.188131e-02 0.1729462 -0.8745306
Asplenium_bulbiferum      0.001396594 3.188131e-02 0.1729462 -0.8745306
Pteridium_aquilinum       0.001396594 3.188131e-02 0.1729462 -0.8745306
Adiantum_pedatum          0.001396594 3.188131e-02 0.1729462 -0.8745306
Cyathea_smithii           0.001396594 3.188131e-02 0.1729462 -0.8745306
Alsophila_tricolor        0.001396594 3.188131e-02 0.1729462 -0.8745306
Alsophila_smithii         0.001396594 3.188131e-02 0.1729462 -0.8745306
Sphaeropteris_medullaris  0.001396594 3.188131e-02 0.1729462 -0.8745306
Dicksonia_squarrosa       0.001396594 3.188131e-02 0.1729462 -0.8745306
Cibotium_barometz         0.001232486 2.306275e-08 0.1729462 -0.9400750
Sticherus_cunninghamii    0.001396594 3.188131e-02 0.1729462 -0.8745306
Dicranopteris_pedata      0.001396594 3.188131e-02 0.1729462 -0.8745306
Dicranopteris_linearis    0.001396594 3.188131e-02 0.1729462 -0.8745306
Osmunda_japonica          0.001396594 3.188131e-02 0.1729462 -0.8745306
Equisetum_hyemale         0.001396594 3.188131e-02 0.1729462 -0.8745306
Equisetum_pratense        0.001396594 3.188131e-02 0.1729462 -0.8745306
Lycopodium_volubile       0.001396594 3.188131e-02 0.1729462 -0.8745306
                          expected_mean expected_var tip_state
Ratibida_pinnata          -0.8745309    1.073704e+10 AM
Heliopsis_helianthoides   -0.8745389    5.181933e+09 AM
Liatris_aspera            -0.8745442    3.043808e+09 AM
Arnica_sororia            -0.8745384    5.585084e+09 AM
Arnica_fulgens            -0.8745384    5.585084e+09 AM
Hymenoxys_richardsonii    -0.8745312    9.059580e+09 AM
Helianthus_agrestis       -0.8745312    3.627737e+10 AM
Helianthus_grosseserratus -0.8745565    6.779518e+08 AM
Helianthus_giganteus      -0.8745565    6.779518e+08 AM
Helianthus_maximiliani    -0.8745325    2.045726e+10 AM
Helianthus_verticillatus  -0.8745329    2.918183e+10 AM
Helianthus_salicifolius   -0.8745309    8.806939e+08 AM
Pappobolus_microphyllus   -0.8745309    3.200424e+09 AM
Helianthus_occidentalis   -0.8745494    1.534562e+09 AM
Helianthus_mollis         -0.8745494    1.534562e+09 AM
Helianthus_silphioides    -0.8745319    2.413715e+10 AM
Helianthus_atrorubens     -0.8745343    2.183101e+10 AM
Helianthus_longifolius    -0.9332443    4.424451e+01 AM
Helianthus_angustifolius  -0.8745520    1.151248e+09 AM
Helianthus_floridanus     -0.8745520    1.151248e+09 AM
Helianthus_petiolaris     -0.8745428    3.150578e+09 AM
Helianthus_neglectus      -0.8745428    3.150578e+09 AM
Helianthus_niveus         -0.8745322    2.240493e+10 AM
Helianthus_praecox        -0.8745502    1.406123e+09 AM
Helianthus_debilis        -0.8745502    1.406123e+09 AM
Helianthus_argophyllus    -0.8745450    2.444724e+09 AM
Helianthus_annuus         -0.8745450    2.444724e+09 AM
Helianthus_cusickii       -0.8745313    3.914334e+10 AM
Helianthus_pauciflorus    -0.8745453    2.361762e+09 AM
Helianthus_radula         -0.8745453    2.361762e+09 AM
⋮                         ⋮             ⋮            ⋮
Dryopteris_lepidopoda     -0.8745307    2.758434e+09 AM
Polystichum_chilense      -0.8745321    3.566154e+10 AM
Blechnum_procerum         -0.8745413    8.827519e+09 AM
Blechnum_novae-zelandiae  -0.8745306    2.468525e+10 AM
Blechnum_lanceolatum      -0.8745311    1.976438e+09 AM
Blechnum_fluviatilis      -0.8745311    1.976438e+09 AM
Blechnum_discolor         -0.8745306    2.468525e+10 AM
Blechnum_orientale        -0.8745362    1.617630e+10 AM
Onoclea_sensibilis        -0.8800241    4.898011e+01 AM
Matteuccia_struthiopteris -0.8800241    4.898011e+01 AM
Athyrium_spinulosum       -0.8745362    1.539363e+10 AM
Athyrium_sinense          -0.8745501    1.416258e+09 AM
Athyrium_monomachii       -0.8745324    2.081099e+10 AM
Cystopteris_sudetica      -0.8745307    2.574114e+09 AM
Asplenium_bulbiferum      -0.8745313    2.259839e+10 NMAM
Pteridium_aquilinum       -0.8745309    1.662541e+10 AM
Adiantum_pedatum          -0.8745349    1.868522e+10 AM
Cyathea_smithii           -0.8745362    1.617631e+10 AM
Alsophila_tricolor        -0.8745477    1.823620e+09 AM
Alsophila_smithii         -0.8745449    2.487935e+09 AM
Sphaeropteris_medullaris  -0.8745372    1.364165e+10 AM
Dicksonia_squarrosa       -0.8745313    3.765180e+10 AM
Cibotium_barometz         -0.9462470    4.364523e+01 AM
Sticherus_cunninghamii    -0.8745314    3.173957e+10 AM
Dicranopteris_pedata      -0.8745538    9.842768e+08 AM
Dicranopteris_linearis    -0.8745613    3.559297e+08 AM
Osmunda_japonica          -0.8745335    2.533094e+10 AM
Equisetum_hyemale         -0.8745376    6.457117e+09 NMAM
Equisetum_pratense        -0.8745361    8.227033e+09 NMAM
Lycopodium_volubile       -0.8745306    2.712345e+00 AM