# ___Phylogenetic PCA___
---------------------------

In [3]:
print(R.version$version.string)

[1] "R version 4.6.0 (2026-04-24 ucrt)"

In [16]:
library("ggplot2")
library("ape")
library("phytools")
library("phylobase")
library("adephylo")
library("readxl")

In [43]:
states <- as.data.frame(readxl::read_xlsx("../../data/chapter2/FRED/subsets/final.xlsx", sheet = "final")[, c("binominal", "state")])
states$binominal <- gsub(states$binominal, pattern = ' ', replacement = '_')

data <- read.csv("../../data/chapter2/FRED/subsets/continuous_raw.csv")

phylogeny <- ape::read.tree("../../data/chapter2/uphylomaker/FRED4_1301.tre")

In [44]:
stopifnot(all(states$binominal %in% data$binominal))
stopifnot(all(states$binominal %in% phylogeny$tip.label))

In [45]:
data

     binominal              F01286       F01287      F01289       F00679
1    Larix_gmelinii         Larix        gmelinii    Pinaceae     0.3194115
2    Larix_gmelinii         Larix        gmelinii    Pinaceae     0.4115552
3    Larix_gmelinii         Larix        gmelinii    Pinaceae     0.5276214
4    Larix_gmelinii         Larix        gmelinii    Pinaceae     0.8469749
5    Larix_gmelinii         Larix        gmelinii    Pinaceae     0.3074501
6    Larix_gmelinii         Larix        gmelinii    Pinaceae     0.4594009
7    Larix_gmelinii         Larix        gmelinii    Pinaceae     0.5276214
8    Larix_gmelinii         Larix        gmelinii    Pinaceae     0.7991291
9    Larix_gmelinii         Larix        gmelinii    Pinaceae     0.3792188
10   Larix_gmelinii         Larix        gmelinii    Pinaceae     0.4114979
11   Larix_gmelinii         Larix        gmelinii    Pinaceae     0.5036986
12   Larix_gmelinii         Larix        gmelinii    Pinaceae     0.6316689
13   Larix_gmelinii         Larix        gmelinii    Pinaceae     0.3125007
14   Larix_gmelinii         Larix        gmelinii    Pinaceae     0.4086550
15   Larix_gmelinii         Larix        gmelinii    Pinaceae     0.6730782
16   Larix_gmelinii         Larix        gmelinii    Pinaceae     0.3004815
17   Larix_gmelinii         Larix        gmelinii    Pinaceae     0.4206743
18   Larix_gmelinii         Larix        gmelinii    Pinaceae     0.5769244
19   Larix_gmelinii         Larix        gmelinii    Pinaceae     0.9615397
20   Larix_gmelinii         Larix        gmelinii    Pinaceae     0.3725969
21   Larix_gmelinii         Larix        gmelinii    Pinaceae     0.4567319
22   Larix_gmelinii         Larix        gmelinii    Pinaceae     0.5769244
23   Larix_gmelinii         Larix        gmelinii    Pinaceae     0.8173090
24   Fraxinus_mandshurica   Fraxinus     mandshurica Oleaceae     0.2884623
25   Fraxinus_mandshurica   Fraxinus     mandshurica Oleaceae     0.3846166
26   Fraxinus_mandshurica   Fraxinus     mandshurica Oleaceae     0.4807706
27   Fraxinus_mandshurica   Fraxinus     mandshurica Oleaceae     0.8533667
28   Fraxinus_mandshurica   Fraxinus     mandshurica Oleaceae     0.2403854
29   Fraxinus_mandshurica   Fraxinus     mandshurica Oleaceae     0.3245205
30   Fraxinus_mandshurica   Fraxinus     mandshurica Oleaceae     0.3966360
⋮    ⋮                      ⋮            ⋮           ⋮            ⋮
5189 Handroanthus_ochraceus Handroanthus ochraceus   Bignoniaceae 0.760364
5190 Handroanthus_ochraceus Handroanthus ochraceus   Bignoniaceae 0.678541
5191 Handroanthus_ochraceus Handroanthus ochraceus   Bignoniaceae 0.592966
5192 Handroanthus_ochraceus Handroanthus ochraceus   Bignoniaceae 0.702249
5193 Handroanthus_ochraceus Handroanthus ochraceus   Bignoniaceae 0.628602
5194 Handroanthus_ochraceus Handroanthus ochraceus   Bignoniaceae 0.544114
5195 Handroanthus_ochraceus Handroanthus ochraceus   Bignoniaceae 0.707943
5196 Handroanthus_ochraceus Handroanthus ochraceus   Bignoniaceae 0.666322
5197 Handroanthus_ochraceus Handroanthus ochraceus   Bignoniaceae 0.717129
5198 Handroanthus_ochraceus Handroanthus ochraceus   Bignoniaceae 0.639956
5199 Handroanthus_ochraceus Handroanthus ochraceus   Bignoniaceae 0.713491
5200 Handroanthus_ochraceus Handroanthus ochraceus   Bignoniaceae 0.610028
5201 Handroanthus_ochraceus Handroanthus ochraceus   Bignoniaceae 0.597345
5202 Handroanthus_ochraceus Handroanthus ochraceus   Bignoniaceae 0.618015
5203 Handroanthus_ochraceus Handroanthus ochraceus   Bignoniaceae 0.599409
5204 Handroanthus_ochraceus Handroanthus ochraceus   Bignoniaceae 0.686993
5205 Handroanthus_ochraceus Handroanthus ochraceus   Bignoniaceae 0.609300
5206 Handroanthus_ochraceus Handroanthus ochraceus   Bignoniaceae 0.694880
5207 Handroanthus_ochraceus Handroanthus ochraceus   Bignoniaceae 0.717104
5208 Handroanthus_ochraceus Handroanthus ochraceus   Bignoniaceae 0.901111
5209 Handroanthus_ochraceus Handroanthus ochraceus   Bignoniaceae 0.746196
5210 Handroanthus_ochraceus Handroanthus ochraceus   Bignoniaceae 0.647419
5211 Handroanthus_ochraceus Handroanthus ochraceus   Bignoniaceae 0.652479
5212 Handroanthus_ochraceus Handroanthus ochraceus   Bignoniaceae 0.704414
5213 Handroanthus_ochraceus Handroanthus ochraceus   Bignoniaceae 0.631103
5214 Handroanthus_ochraceus Handroanthus ochraceus   Bignoniaceae 0.740062
5215 Handroanthus_ochraceus Handroanthus ochraceus   Bignoniaceae 0.739066
5216 Handroanthus_ochraceus Handroanthus ochraceus   Bignoniaceae 0.666566
5217 Handroanthus_ochraceus Handroanthus ochraceus   Bignoniaceae 0.639820
5218 Handroanthus_ochraceus Handroanthus ochraceus   Bignoniaceae 0.743855
     F00727     F00709
1     32.211568 0.3542858
2     25.480815 0.2942859
3     12.980828 0.3828573
4      6.250067 0.3342859
5     34.615414 0.3828572
6     26.442353 0.2600002
7     14.423135 0.3514288
8      6.250067 0.3457145
9     43.750027 0.3457144
10    27.884660 0.2685716
11    18.269287 0.2828574
12     8.653912 0.3600002
13    25.961568 0.4571429
14    22.596200 0.3142859
15    11.057752 0.3085716
16    36.057721 0.3657144
17    24.038507 0.3085716
18    13.461597 0.3857144
19     5.288529 0.3485716
20    34.615413 0.2485715
21    24.038507 0.3228573
22    12.980828 0.4114287
23     5.288529 0.5342858
24    78.846169 0.2312058
25    41.826962 0.2765959
26    16.826980 0.3475179
27     5.288529 0.4099292
28   112.019221 0.2113476
29    50.961573 0.2680853
30    27.403898 0.2936172
⋮    ⋮          ⋮
5189  9.333876  0.2094764
5190  9.885150  0.2272073
5191  9.512751  0.3128636
5192 10.273513  0.2140365
5193 14.266517  0.1902167
5194 24.029145  0.1542217
5195  9.203546  0.2247548
5196 15.293734  0.1661285
5197  7.926504  0.2496891
5198 12.441642  0.2169800
5199  6.955624  0.2820500
5200 10.241263  0.2776844
5201 15.255128  0.1812942
5202 10.114883  0.2732840
5203 13.921548  0.2075042
5204 11.656564  0.1805156
5205 14.371084  0.2012636
5206  9.747348  0.2200709
5207 10.019846  0.2070031
5208  6.420508  0.1840805
5209  7.518326  0.2391492
5210 13.869664  0.1873901
5211 12.059466  0.2207273
5212  9.609298  0.2299801
5213 13.416594  0.2160985
5214  8.685170  0.2240915
5215  8.855820  0.2281547
5216  9.584048  0.2283787
5217 10.362667  0.2653314
5218  8.333673  0.2301904

In [51]:
aggregate(x = data, by = list(data$binominal), FUN = mean, na.rm = TRUE)

Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"
Warning message in mean.default(X[[i]], ...):
"argument is not numeric or logical: returning NA"

     Group.1                  binominal F01286 F01287 F01289 F00679
1    Abies_alba               NA        NA     NA     NA     0.5530000
2    Abies_nephrolepis        NA        NA     NA     NA     0.4152333
3    Acacia_auriculiformis    NA        NA     NA     NA     0.4911167
4    Acacia_crassicarpa       NA        NA     NA     NA     0.2259300
5    Acacia_mangium           NA        NA     NA     NA     0.2525500
6    Acer_barbinerve          NA        NA     NA     NA     0.2523000
7    Acer_campbellii          NA        NA     NA     NA     0.1897500
8    Acer_campestre           NA        NA     NA     NA     0.4210000
9    Acer_caudatum            NA        NA     NA     NA     0.2359000
10   Acer_coriaceifolium      NA        NA     NA     NA     0.3000000
11   Acer_davidii             NA        NA     NA     NA     0.4060971
12   Acer_fabri               NA        NA     NA     NA     0.1939350
13   Acer_laurinum            NA        NA     NA     NA     0.6289278
14   Acer_negundo             NA        NA     NA     NA     0.2790000
15   Acer_pictum              NA        NA     NA     NA     0.2766000
16   Acer_platanoides         NA        NA     NA     NA     0.4280410
17   Acer_pseudoplatanus      NA        NA     NA     NA     0.3625263
18   Acer_rubrum              NA        NA     NA     NA     0.5517871
19   Acer_saccharum           NA        NA     NA     NA     0.5576867
20   Acer_tataricum           NA        NA     NA     NA     0.2331333
21   Acer_tegmentosum         NA        NA     NA     NA     0.3482400
22   Acer_triflorum           NA        NA     NA     NA     0.2341000
23   Acer_truncatum           NA        NA     NA     NA     0.4280036
24   Achillea_millefolium     NA        NA     NA     NA     0.3295644
25   Ackama_rosifolia         NA        NA     NA     NA     0.3606385
26   Acronychia_pedunculata   NA        NA     NA     NA     0.5239360
27   Actaea_cimicifuga        NA        NA     NA     NA     0.2670500
28   Actinidia_kolomikta      NA        NA     NA     NA     0.2300000
29   Actinodaphne_henryi      NA        NA     NA     NA     0.7845667
30   Adenocaulon_himalaicum   NA        NA     NA     NA     0.1734000
⋮    ⋮                        ⋮         ⋮      ⋮      ⋮      ⋮
1272 Vernonia_fasciculata     NA        NA     NA     NA     0.3100000
1273 Veronica_persica         NA        NA     NA     NA     0.2300000
1274 Veronica_spuria          NA        NA     NA     NA     0.1867000
1275 Veronicastrum_virginicum NA        NA     NA     NA     0.3000000
1276 Viburnum_dentatum        NA        NA     NA     NA     0.5351640
1277 Viburnum_stipitatum      NA        NA     NA     NA     0.9775000
1278 Viburnum_tinus           NA        NA     NA     NA     0.4532750
1279 Vicia_americana          NA        NA     NA     NA     0.3631783
1280 Vicia_villosa            NA        NA     NA     NA     0.4300000
1281 Viola_adunca             NA        NA     NA     NA     0.2411500
1282 Vitex_lucens             NA        NA     NA     NA     0.5437833
1283 Vitis_amurensis          NA        NA     NA     NA     0.2750500
1284 Vitis_vinifera           NA        NA     NA     NA     0.5188250
1285 Vitis_vulpina            NA        NA     NA     NA     0.6784643
1286 Weinmannia_elliptica     NA        NA     NA     NA     0.4092514
1287 Weinmannia_fagaroides    NA        NA     NA     NA     0.4170000
1288 Weinmannia_magnifolia    NA        NA     NA     NA     0.5128000
1289 Weinmannia_microphylla   NA        NA     NA     NA     0.3812378
1290 Weinmannia_ovata         NA        NA     NA     NA     0.3372000
1291 Weinmannia_silvicola     NA        NA     NA     NA     0.3831200
1292 Wendlandia_uvariifolia   NA        NA     NA     NA     0.2241700
1293 Withania_frutescens      NA        NA     NA     NA     0.3918000
1294 Wurfbainia_villosa       NA        NA     NA     NA     0.2319556
1295 Xanthisma_spinulosum     NA        NA     NA     NA     0.3163000
1296 Xanthophyllum_flavescens NA        NA     NA     NA     0.7474667
1297 Xanthophyllum_tenue      NA        NA     NA     NA     0.4357500
1298 Zabelia_biflora          NA        NA     NA     NA     0.5292000
1299 Zamia_lucayana           NA        NA     NA     NA     0.3275139
1300 Zizia_aurea              NA        NA     NA     NA     0.3100000
1301 Zygia_inaequalis         NA        NA     NA     NA     0.3670000
     F00727     F00709
1     32.026667 0.2443333
2     27.045857 0.2797059
3     37.353333 0.2933333
4    108.280000 0.3600000
5     99.190000 0.2900000
6    143.678973 0.1528288
7     79.072418 0.4550000
8     30.970000 0.2800000
9     87.394935 0.2600000
10    88.433333 0.1900000
11    49.627960 0.3545364
12   142.065000 0.2900000
13    12.063187 0.3152168
14    38.230000 0.5367000
15    76.069844 0.2343332
16    24.100245 0.4320000
17    34.779778 0.4199622
18    27.605311 0.2144800
19    30.443644 0.1979305
20   172.478478 0.1462190
21    76.069951 0.1457709
22   110.633221 0.2270829
23    37.561583 0.2873413
24   193.855144 0.1307157
25    51.988595 0.1996258
26    33.192525 0.2930184
27   117.113062 0.2376004
28   224.523768 0.1078125
29     7.258719 0.3291825
30   192.911690 0.2218750
⋮    ⋮          ⋮
1272 123.000000 0.11000000
1273 503.000000 0.08000000
1274 226.915833 0.16363636
1275 131.000000 0.11000000
1276   8.660357 0.54484212
1277   4.016494 0.33165217
1278  11.269931 0.63558709
1279 165.485922 0.09637506
1280  60.000000 0.12000000
1281  83.219934 0.35735294
1282  41.355839 0.11565265
1283 104.011337 0.17336538
1284  14.869913 0.46471757
1285  21.186656 0.16436740
1286  23.484052 0.32908340
1287   9.214338 0.79536424
1288   8.534897 0.56521739
1289  22.948549 0.48703217
1290  14.800770 0.75600000
1291  44.072685 0.22687275
1292  45.270000 0.43000000
1293   5.831897 0.46133148
1294 187.404807 0.13316854
1295 115.717500 0.10666667
1296   6.374235 0.46572851
1297  25.229250 0.28625000
1298  30.947057 0.14669604
1299  58.872450 0.21967512
1300 100.000000 0.13000000
1301  26.160000 0.36200000

In [46]:
phytools::phyl.pca(tree = phylogeny, )

function (tree, Y, method = "BM", mode = "cov", ...)
{
    if (hasArg(opt))
        opt <- list(...)$opt
    else opt <- "ML"
    if (!inherits(tree, "phylo"))
        stop("tree should be an object of class \"phylo\".")
    if (length(strsplit(mode, split = "")[[1]]) <= 2) {
        message(paste("mode = \"", mode, "\" not a valid option; setting mode = \"cov\"",
            sep = ""))
        mode <- "cov"
    }
    if (all(strsplit(mode, split = "")[[1]] == strsplit("correlation",
        split = "")[[1]][1:length(strsplit(mode, split = "")[[1]])]))
        mode <- "corr"
    else if (all(strsplit(mode, split = "")[[1]] == strsplit("covariance",
        split = "")[[1]][1:length(strsplit(mode, split = "")[[1]])]))
        mode <- "cov"
    else {
        message(paste("mode = \"", mode, "\" not a valid option; setting mode = \"cov\"",
            sep = ""))
        mode = "cov"
    }
    if (opt == "REML")
        object <- reml_phyl.pca(tree, Y, method, mode, ...)
    else object <- ml_phyl.pca(tree, Y, method, mode, ...)
    object
}
<bytecode: 0x00000280f17a60f0>
<environment: namespace:phytools>

In [39]:
phylobase::phylo4d(x = phylogeny, tip.data = data)

ERROR: Error in formatData(phy = x, dt = tip.data, type = "tip", ...): Your tip data are being matched to internal nodes. Make sure that your data identifiers are correct.