# ___Phylogenetic traversal of ACEs___
---------------------------------------------------

In [1]:
print(R.version$version.string)

[1] "R version 4.5.2 (2025-10-31 ucrt)"

In [1]:
suppressPackageStartupMessages({
    library("ape")
    library("phytools")
    library("corHMM")
    library("diversitree")
})

set.seed(2026-1-26)

In [2]:
STATES <- read.csv("../../data/chapter2/FREDv3subset/finalized_states_395_species.csv", stringsAsFactors = TRUE)[, c("binominal", "state")] # finalized mycorrhizal states
COLLAB_AXIS <- read.csv("../../data/chapter2/FREDv3subset/collab_ord1_species_avgs_SRL_RD.csv", stringsAsFactors = TRUE) # first order species averaged RD and SRL values
MERGED <- merge(x = STATES, y = COLLAB_AXIS, by = "binominal") # merge the two datasets into one, based on the binominal names
stopifnot(nrow(MERGED)==395)

PHYLOGENY <- ape::multi2di(ape::read.tree("../../data/chapter2/uphylomaker/FRED_subset_collab_395sp.tre")) # phylogenetic tree created for the 395 species using U.PhyloMaker
stopifnot(length(PHYLOGENY$tip.label)==395)

# MERGED contains spaces in the binominal names - replace that with underscores; and '/' in mycorrhizal states that need to be removed
data <- data.frame(binominal = gsub(MERGED$binominal, pattern = ' ', replacement = '_'), RD = MERGED$F00679, SRL = MERGED$F00727, myco = gsub(x = MERGED$state, pattern = '/', replacement = ''))
matched_row_indices <- match(PHYLOGENY$tip.label, data$binominal)
stopifnot(all(data$binominal[matched_row_indices] == PHYLOGENY$tip.label))
data <- data[matched_row_indices, ] # reorder the dataset to match the species order in the phylogeny
stopifnot(all(data$binominal == PHYLOGENY$tip.label))
stopifnot(length(unique(data$binominal)) == length(data$binominal))

In [3]:
# FOR CONVENIRNCE
RD <- setNames(object = data$RD, nm = data$binominal)
SRL <- setNames(object = data$SRL, nm = data$binominal)
STATES <- setNames(object = data$myco, nm = data$binominal)

In [4]:
table(STATES) # welp

STATES
   AM AMEcM  AMNM   EcM   ErM    NM
  300    15     8    65     3     4

# PLOT THE PHYLOGENY AND NODE & TIP NUMBERS, IT'LL HELP IN TRACING DOWN CHANGES AND SHIFTS IN TRAITS

par(mar=c(0, 0, 0, 0))
png(filename = "../../plots/FRED_subset_collab_395sp_nodes_n_tips.png", width = 18000, height = 18000, units = "px", res = 300)
phytools::plotTree(tree = PHYLOGENY, ftype = "i", fsize = 1.2, type = "fan", lwd = 1, offset = 4)
# with interactive left to default, got a warning for every label
phytools::labelnodes(text = 1:(PHYLOGENY$Nnode + length(PHYLOGENY$tip.label)), node = 1:(PHYLOGENY$Nnode + length(PHYLOGENY$tip.label)), cex = 1, interactive = FALSE)
dev.off()

### ___ACE of discrete categorical traits using `ape`, `corHMM`, `phytools` & `diversitree`___
------------------------------------------------------

In [5]:
ape::is.ultrametric(PHYLOGENY) # diversitree requires the phylogeny to be ultrametric

[1] TRUE

In [6]:
# diversitree::make.mkn requires the states to be encodes as numbers
STATES_TO_NUMERIC <- setNames(seq_along(unique(STATES)), unique(STATES)) # numeric encoding of the discrete character states
STATES_NUMERIC <- setNames(unname(STATES_TO_NUMERIC[unname(STATES)]), names(STATES)) # named vector for states with numeric encodings

In [7]:
# diversitree::make.mk2() can only be used with binary state discrete characters
fnlikelihood <- diversitree::make.mkn(tree = PHYLOGENY, states = STATES_NUMERIC, k = length(unique(STATES)))

In [8]:
fnlikelihood

Mk(n) likelihood function:
  * Parameter vector takes 30 elements:
     - q12, q13, q14, q15, q16, q21, q23, q24, q25, q26, q31, q32, q34,
       q35, q36, q41, q42, q43, q45, q46, q51, q52, q53, q54, q56, q61,
       q62, q63, q64, q65
  * Function takes arguments (with defaults)
     - pars: Parameter vector
     - root [ROOT.OBS]: Type of root treatment
     - root.p [NULL]: Vector of root state probabilities
     - intermediates [FALSE]: Also return intermediate values?
  * Phylogeny with 395 tips and 394 nodes
     - Taxa: Anaphalis_aureopunctata, Anaphalis_hancockii, ...
  * References:
     - Pagel (1994)
     - Lewis (2001)
R definition:
function (pars, root = ROOT.OBS, root.p = NULL, intermediates = FALSE)

In [40]:
# pars argument of the likelihood function
# for make.mkn, a vector of k(k-1) parameters, in the order q12,q13,...q1k, q21,q23,...,q2k,...qk(k-1),
# corresponding to the off-diagonal elements of the Q matrix in row order. The order of parameters can be seen by running argnames(f)

# in our case k is 6, so we need (6x(6-1)) 30 values???

In [10]:
tm <- Sys.time()
# this is an ARD model!
dtmod <- diversitree::find.mle(func = fnlikelihood, x.init = rep(x = 1, times = 30), # x.init and any extra args will get passed to the likelihood function
                      root = diversitree::ROOT.FLAT)
tm <- Sys.time() - tm

Warning message in mle.search(func2, x.init, control, lower, upper):
"Convergence problems in find.mle (subplex): number of function evaluations exceeds 'maxit'"

In [14]:
dtmod$lnLik

[1] -277.7409

In [57]:
#----------------------------------------------------------------------------------------------------------------------------------------------------------
# choosing the ARD model for mycorrhizal state evolution as it has been demonstrated that different transitions happen at different rates
# and some transitions are prectically irreversible compared to others
#----------------------------------------------------------------------------------------------------------------------------------------------------------

# there are multiple ways to do ACE of discrete characters 
# ace_mystates_rr <- phytools::rerootingMethod(tree = PHYLOGENY, x = STATES, model = "ARD") - phytools::rerootingMethod method should not be used with non-symmetrical rate models of evolution
# read more here - https://blog.phytools.org/2023/06/decommissioning-rerootingmethod-and.html
ace_mystates_hmm <- corHMM::corHMM(phy = PHYLOGENY, data = data[, c("binominal", "myco")], model = "ARD", node.states = "marginal", rate.cat = 1)
ace_mystates_ape <- ape::ace(phy = PHYLOGENY, x = STATES, type = "discrete", method = "ML", model = "ARD", marginal = FALSE) # ape::ace used a non traditional way to compute marginal ACEs, see its documentation for more details
# setting marginal = FALSE actually returns the marginal ACEs, see the documentation of ape::ace for more details
ace_mystates_ancr <- phytools::ancr(phytools::fitMk(tree = PHYLOGENY, x = STATES, model = "ARD"))
ace_mystates_dvt <- diversitree::asr.marginal()

You specified 'fixed.nodes=FALSE' but included a phy object with node labels. These node labels have been removed.

Warning message in corHMM::corHMM(phy = PHYLOGENY, data = data[, c("binominal", :
"Branch lengths of 0 detected. Adding 1e-5 to these branches."

State distribution in data:
States:	1	2	3	4	5	6
Counts:	300	15	8	65	3	4
Beginning thorough optimization search -- performing 0 random restarts
Finished. Inferring ancestral states using marginal reconstruction.

Warning message in sqrt(diag(solve(h))):
"NaNs produced"

In [58]:
ace_mystates_ape

    Ancestral Character Estimation

Call: ape::ace(x = STATES, phy = PHYLOGENY, type = "discrete", method = "ML",
    model = "ARD", marginal = FALSE)

    Log-likelihood: -181.3674

Rate index matrix:
      AM AMEcM AMNM EcM ErM NM
AM     .     6   11  16  21 26
AMEcM  1     .   12  17  22 27
AMNM   2     7    .  18  23 28
EcM    3     8   13   .  24 29
ErM    4     9   14  19   . 30
NM     5    10   15  20  25  .

Parameter estimates:
 rate index estimate std-err
          1   0.1675     NaN
          2   0.2740  0.1254
          3   0.0000     NaN
          4   0.0000     NaN
          5   0.0893     NaN
          6   0.0001  0.0006
          7   0.1518  0.0526
          8   0.0012  0.0028
          9   0.1165     NaN
         10   0.1282  0.0334
         11   0.0028  0.0018
         12   0.0425     NaN
         13   0.0000     NaN
         14   0.1164     NaN
         15   0.0822  0.0977
         16   0.0000  0.0008
         17   0.1545     NaN
         18   0.2093  0.1706
         19   0.2057     NaN
         20   0.2056     NaN
         21   0.0000  0.0013
         22   0.0446     NaN
         23   0.0940  0.4077
         24   0.0116     NaN
         25   0.0918     NaN
         26   0.0000  0.0007
         27   0.0249     NaN
         28   0.1182  0.3213
         29   0.0082  0.0023
         30   0.1190     NaN

Scaled likelihoods at the root (type '...$lik.anc' to get them for all nodes):
       AM     AMEcM      AMNM       EcM       ErM        NM
0.1780089 0.1676519 0.1678401 0.1578816 0.1634363 0.1651812

In [59]:
ace_mystates_ape$lik.anc

                   AM           AMEcM        AMNM         EcM
                   0.1780089    0.1676518788 0.1678401104 1.578816e-01
Spermatophyta      0.6310923    0.0084811117 0.0046860970 3.366761e-01
Mesangiospermae    0.9977983    0.0008959747 0.0007030378 4.115483e-05
mrcaott2ott121     0.9976928    0.0009168643 0.0008248789 5.344119e-06
eudicotyledons     0.9955824    0.0018530047 0.0015131992 1.288869e-04
mrcaott2ott969     0.9940670    0.0023076272 0.0023267179 7.443955e-05
Pentapetalae       0.9924739    0.0039979010 0.0019058349 5.098264e-05
mrcaott248ott19688 0.9834832    0.0065906228 0.0053868733 6.934968e-04
mrcaott248ott557   0.9799111    0.0082624305 0.0065630318 3.467028e-04
mrcaott248ott27233 0.9797556    0.0108912152 0.0042882178 4.049869e-04
mrcaott248ott650   0.9774911    0.0117853692 0.0054856190 2.174150e-04
mrcaott248ott320   0.9757427    0.0123543061 0.0042993860 1.789938e-03
campanulids        0.9673735    0.0145043475 0.0055300586 4.354440e-03
mrcaott320ott1673  0.9670032    0.0110497531 0.0039363376 1.047386e-02
                   0.9899060    0.0029321117 0.0019047774 2.115764e-03
                   0.9881637    0.0055348484 0.0028746640 3.499209e-04
                   0.9843578    0.0075760994 0.0035912460 6.109644e-04
                   0.9816607    0.0081978836 0.0031675447 2.314347e-03
                   0.8086079    0.0168679193 0.1465737446 2.002443e-04
                   0.9798027    0.0102673418 0.0040901042 7.688703e-04
                   0.9966889    0.0016731319 0.0009606002 4.263214e-06
                   0.9965312    0.0016880241 0.0011374858 2.134477e-07
                   0.9994221    0.0002588024 0.0002538513 7.811364e-09
                   0.9994209    0.0002587232 0.0002553313 2.040185e-10
                   0.9995146    0.0002009126 0.0002268013 7.251092e-09
                   0.9995146    0.0002009126 0.0002268013 7.251092e-09
mrcaott1673ott2128 0.9661098    0.0109185195 0.0038878062 1.182774e-02
                   0.9526553    0.0044630855 0.0027037722 3.370560e-02
                   0.9895208    0.0030718166 0.0019303927 2.146189e-03
                   0.9885059    0.0057224691 0.0024715783 3.932248e-04
⋮                  ⋮            ⋮            ⋮            ⋮
                   1.952400e-06 3.703915e-03 1.373258e-03 9.775860e-01
                   5.950434e-06 5.821818e-03 2.067447e-03 9.720363e-01
                   1.788712e-06 7.121708e-03 2.580946e-03 9.697772e-01
                   6.305267e-08 4.062671e-03 2.035501e-03 9.829753e-01
                   8.628467e-07 7.744318e-03 3.126837e-03 9.623560e-01
                   7.746716e-07 8.962482e-03 4.402356e-03 9.510712e-01
                   2.572344e-05 9.388769e-03 3.050990e-03 9.582853e-01
                   1.934132e-06 5.784774e-03 2.082286e-03 9.758888e-01
                   4.824249e-08 4.448854e-03 2.321011e-03 9.771865e-01
                   3.732906e-08 4.272236e-03 2.652649e-03 9.753601e-01
                   1.461767e-06 1.946789e-03 1.044126e-03 9.873188e-01
                   5.631226e-08 2.283654e-03 1.378036e-03 9.829639e-01
                   3.557412e-12 2.817704e-05 1.758832e-05 9.998826e-01
                   5.492356e-07 1.160760e-03 6.828667e-04 9.930566e-01
                   5.893573e-01 8.472562e-03 4.897637e-03 3.774475e-01
                   7.091522e-01 7.982216e-03 4.429964e-03 2.616004e-01
                   7.444630e-01 7.523753e-03 4.256912e-03 2.283067e-01
                   7.046422e-01 1.149511e-02 6.671445e-03 2.534363e-01
                   8.539510e-01 1.393533e-02 5.449827e-03 1.096627e-01
                   8.725718e-01 8.939484e-03 4.152566e-03 1.016949e-01
                   8.849891e-01 7.961212e-03 4.609388e-03 8.848971e-02
                   5.287769e-01 2.067592e-02 1.295760e-02 3.938916e-01
                   9.319003e-01 1.337409e-02 4.909850e-03 3.812913e-02
                   9.810773e-01 4.199700e-03 2.400612e-03 7.229412e-03
                   9.860552e-01 5.010184e-03 2.326563e-03 2.864414e-03
                   9.843833e-01 6.603714e-03 2.663197e-03 2.479721e-03
                   9.966635e-01 1.434279e-03 9.050508e-04 2.978402e-05
                   9.966635e-01 1.434279e-03 9.050508e-04 2.978402e-05
                   9.299637e-01 4.503584e-03 2.863192e-03 5.550879e-02
                   4.248050e-01 8.534802e-03 5.298187e-03 5.388290e-01
                   ErM          NM
                   1.634363e-01 1.651812e-01
Spermatophyta      1.046941e-02 8.594939e-03
Mesangiospermae    1.866265e-04 3.749249e-04
mrcaott2ott121     1.821930e-04 3.778822e-04
eudicotyledons     3.336534e-04 5.888886e-04
mrcaott2ott969     4.406896e-04 7.835524e-04
Pentapetalae       5.261451e-04 1.045281e-03
mrcaott248ott19688 1.511159e-03 2.334679e-03
mrcaott248ott557   1.854204e-03 3.062496e-03
mrcaott248ott27233 1.664066e-03 2.995946e-03
mrcaott248ott650   1.743825e-03 3.276681e-03
mrcaott248ott320   2.334228e-03 3.479459e-03
campanulids        3.532055e-03 4.705581e-03
mrcaott320ott1673  3.427214e-03 4.109653e-03
                   1.341661e-03 1.799708e-03
                   1.149820e-03 1.927028e-03
                   1.486859e-03 2.377077e-03
                   1.978408e-03 2.681166e-03
                   1.060392e-02 1.714626e-02
                   2.008455e-03 3.062486e-03
                   1.663504e-04 5.067789e-04
                   1.462481e-04 4.968019e-04
                   5.026729e-06 6.024742e-05
                   4.944906e-06 6.014186e-05
                   5.216019e-06 5.248532e-05
                   5.216019e-06 5.248532e-05
mrcaott1673ott2128 3.310672e-03 3.945456e-03
                   3.165319e-03 3.306942e-03
                   1.444361e-03 1.886446e-03
                   1.132108e-03 1.774693e-03
⋮                  ⋮            ⋮
                   0.0111108741 6.223990e-03
                   0.0122175919 7.850913e-03
                   0.0121733042 8.345087e-03
                   0.0061696890 4.756822e-03
                   0.0161878817 1.058410e-02
                   0.0214889201 1.407427e-02
                   0.0178059451 1.144328e-02
                   0.0096680949 6.574092e-03
                   0.0095096186 6.533962e-03
                   0.0104982373 7.216725e-03
                   0.0059552978 3.733548e-03
                   0.0082140021 5.160349e-03
                   0.0000386008 3.298574e-05
                   0.0030021994 2.096981e-03
                   0.0109994506 8.825577e-03
                   0.0091066273 7.728605e-03
                   0.0083082699 7.141393e-03
                   0.0126777623 1.107721e-02
                   0.0085505911 8.450624e-03
                   0.0064377341 6.203507e-03
                   0.0071304990 6.820096e-03
                   0.0233932100 2.030475e-02
                   0.0055898799 6.096737e-03
                   0.0023169801 2.776042e-03
                   0.0016389772 2.104643e-03
                   0.0016737532 2.196340e-03
                   0.0003394957 6.278988e-04
                   0.0003394957 6.278988e-04
                   0.0036076837 3.553009e-03
                   0.0128654410 9.667565e-03

In [60]:
ace_mystates_ancr

Marginal ancestral state estimates:
          AM    AMEcM     AMNM      EcM ErM       NM
396 0.127694 0.002593 0.358596 0.001056   0 0.510062
397 0.541962 0.000657 0.204941 0.001657   0 0.250783
398 0.999895 0.000000 0.000087 0.000000   0 0.000019
399 0.999904 0.000000 0.000081 0.000000   0 0.000015
400 0.999756 0.000000 0.000232 0.000000   0 0.000012
401 0.999835 0.000000 0.000156 0.000000   0 0.000009
...

Log-likelihood = -128.722103

In [61]:
ace_mystates_ancr$ace

    AM           AMEcM        AMNM         EcM          ErM NM
396 0.1276937    2.592872e-03 3.585956e-01 1.056257e-03 0   5.100616e-01
397 0.5419618    6.572441e-04 2.049406e-01 1.657275e-03 0   2.507831e-01
398 0.9998947    4.907078e-13 8.655514e-05 1.959951e-08 0   1.867626e-05
399 0.9999042    5.140939e-12 8.077173e-05 7.768918e-09 0   1.497816e-05
400 0.9997561    1.896532e-10 2.315145e-04 2.751930e-08 0   1.240614e-05
401 0.9998345    5.011078e-10 1.559156e-04 6.784768e-08 0   9.492852e-06
402 0.9999795    1.427418e-11 1.530185e-05 4.787841e-09 0   5.155376e-06
403 0.9995313    4.819200e-08 2.876598e-04 6.361608e-08 0   1.808865e-04
404 0.9996743    1.036743e-08 2.074287e-04 2.330845e-07 0   1.180267e-04
405 0.9999722    5.051059e-11 2.100304e-05 4.661238e-08 0   6.766740e-06
406 0.9999872    6.379436e-11 1.097736e-05 3.623801e-08 0   1.769265e-06
407 0.9999231    3.953910e-10 7.248367e-05 1.027463e-07 0   4.334214e-06
408 0.9998600    1.660241e-08 1.242247e-04 8.684944e-07 0   1.493458e-05
409 0.9998308    1.057266e-08 1.477171e-04 9.752908e-07 0   2.049082e-05
410 0.9997573    5.797366e-09 2.085010e-04 2.188047e-06 0   3.195804e-05
411 0.9998903    3.539722e-10 1.021970e-04 1.673830e-07 0   7.353846e-06
412 0.9998165    1.127114e-09 1.775026e-04 1.955289e-07 0   5.815838e-06
413 0.9986850    8.514612e-10 1.300591e-03 1.477050e-07 0   1.430946e-05
414 0.8908165    9.642406e-11 1.091072e-01 5.259191e-09 0   7.629540e-05
415 0.9996511    1.016382e-09 3.408518e-04 2.190292e-07 0   7.876266e-06
416 0.9999991    1.412242e-13 7.807043e-07 4.286240e-09 0   8.605148e-08
417 0.9999996    5.278885e-13 3.669473e-07 1.470721e-09 0   4.074349e-08
418 1.0000000    4.018682e-17 2.105349e-08 5.912851e-11 0   2.324324e-09
419 1.0000000    2.820693e-16 1.701719e-08 2.520290e-11 0   1.809604e-09
420 1.0000000    3.560887e-17 3.077365e-08 5.615305e-11 0   4.236995e-09
421 1.0000000    3.560887e-17 3.077365e-08 5.615305e-11 0   4.236995e-09
422 0.9997886    1.078454e-08 1.847530e-04 8.350571e-07 0   2.583256e-05
423 0.9989522    4.161533e-07 8.788566e-04 1.259350e-05 0   1.558935e-04
424 0.9998500    3.812383e-09 1.261271e-04 1.388228e-06 0   2.248882e-05
425 0.9999706    3.412240e-10 2.532836e-05 1.736289e-07 0   3.908653e-06
⋮   ⋮            ⋮            ⋮            ⋮            ⋮   ⋮
760 3.747545e-10 8.321947e-07 5.724922e-17 9.999992e-01 0   2.608158e-17
761 1.400946e-08 1.847843e-08 7.890088e-15 1.000000e+00 0   1.191018e-15
762 6.046204e-09 2.480107e-09 1.495440e-15 1.000000e+00 0   2.186866e-16
763 5.053852e-10 1.159950e-10 1.081151e-17 1.000000e+00 0   1.557960e-18
764 2.577090e-09 9.590326e-10 2.722059e-16 1.000000e+00 0   3.952281e-17
765 2.988342e-09 3.704244e-10 3.627790e-16 1.000000e+00 0   5.218778e-17
766 5.057256e-08 7.906948e-08 9.696964e-14 9.999999e-01 0   1.477900e-14
767 5.578643e-09 3.321568e-09 1.272474e-15 1.000000e+00 0   1.877580e-16
768 2.777672e-10 5.862097e-11 3.255867e-18 1.000000e+00 0   4.675287e-19
769 3.360149e-10 1.714490e-11 4.731411e-18 1.000000e+00 0   6.754122e-19
770 6.915672e-09 2.114865e-07 1.897645e-15 9.999998e-01 0   4.708846e-16
771 9.104328e-10 2.564709e-08 3.509605e-17 1.000000e+00 0   8.228641e-18
772 3.347319e-12 1.329052e-12 4.812771e-22 1.000000e+00 0   6.965284e-23
773 1.711679e-08 1.515628e-06 9.393854e-15 9.999985e-01 0   3.603807e-15
774 1.367763e-01 2.960188e-04 3.135417e-01 8.823762e-05 0   5.492978e-01
775 2.974442e-01 8.823235e-05 2.166888e-01 7.443387e-05 0   4.857044e-01
776 3.636997e-01 5.923947e-05 1.559340e-01 3.593924e-05 0   4.802711e-01
777 3.600053e-01 3.542357e-05 1.071367e-01 4.652134e-06 0   5.328179e-01
778 4.717033e-01 3.814868e-06 8.092559e-02 4.044279e-06 0   4.473633e-01
779 5.351983e-01 2.349005e-06 6.296396e-02 5.313256e-06 0   4.018301e-01
780 5.781071e-01 1.749311e-06 4.509456e-02 1.817272e-06 0   3.767948e-01
781 4.600477e-01 6.451110e-05 4.298012e-02 1.953242e-06 0   4.969057e-01
782 7.866973e-01 2.410142e-07 2.892976e-02 3.355313e-06 0   1.843693e-01
783 9.883858e-01 1.296482e-08 2.688250e-03 2.134635e-06 0   8.923826e-03
784 9.987425e-01 2.674117e-09 3.945262e-04 5.921852e-07 0   8.624234e-04
785 9.996828e-01 5.099497e-09 1.450516e-04 6.994039e-07 0   1.714632e-04
786 9.999888e-01 3.163717e-13 5.502585e-06 5.164346e-09 0   5.647065e-06
787 9.999888e-01 3.163717e-13 5.502585e-06 5.164346e-09 0   5.647065e-06
788 9.256696e-01 4.622304e-06 3.071278e-02 1.007086e-04 0   4.351228e-02
789 6.505862e-02 4.742488e-04 3.846019e-01 2.197653e-05 0   5.498433e-01

In [ ]:
ace_mystates_dvt <- diversitree::

In [ ]:
#--------------------------------
# ACE OF CONTINUOUS TRAITS
#--------------------------------

ace_srl_fastanc <- phytools::fastAnc(tree = PHYLOGENY, x = SRL)

In [ ]:
# WE DO HAVE POLYTOMIES IN OUR PHYLOGENY :(

In [6]:
ace_mystates_hmm # WE DO SEE TRANSITION RATE DIFFERENCES

Fit
      -lnL      AIC     AICc Rate.cat ntax
 -127.3412 314.6824 319.7923        1  395

Legend
      1       2       3       4       5       6
   "AM" "AMEcM"  "AMNM"   "EcM"   "ErM"    "NM"

Rates
             (1,R1)      (2,R1)       (3,R1)       (4,R1)       (5,R1)
(1,R1)           NA 0.000322027 0.0009748366 0.0002015374 6.729752e-05
(2,R1) 1.000336e-09          NA 0.0000000010 0.0174455509 1.000000e-09
(3,R1) 1.691330e-02 0.000000001           NA 0.0000000010 1.000000e-09
(4,R1) 1.299848e-03 0.000000001 0.0000000010           NA 1.000000e-09
(5,R1) 1.000000e-09 0.000000001 0.0000000010 0.0000000010           NA
(6,R1) 1.000000e-09 0.000000001 0.0071676917 0.0000000010 1.000000e-09
             (6,R1)
(1,R1) 0.0000000010
(2,R1) 0.0000000010
(3,R1) 0.0102782964
(4,R1) 0.0000000010
(5,R1) 0.0009739048
(6,R1)           NA

Arrived at a reliable solution

In [23]:
head(ace_mystates_hmm$states) # probabilities of each internal node of the phylogeny belonging to the given states

     (1,R1)    (2,R1)       (3,R1)       (4,R1)       (5,R1)       (6,R1)
[1,] 0.7384076 1.040770e-04 0.0993487387 6.261923e-03 6.054074e-04 1.552723e-01
[2,] 0.8500365 7.905156e-04 0.0746536180 5.613651e-03 2.862179e-05 6.887709e-02
[3,] 0.9991832 9.825375e-13 0.0008165587 7.341792e-08 1.816180e-15 1.231038e-07
[4,] 0.9992081 2.686675e-11 0.0007917985 3.029895e-08 2.461497e-14 8.734257e-08
[5,] 0.9989132 2.536349e-10 0.0010865789 5.341592e-08 3.150591e-12 2.026010e-07
[6,] 0.9990792 3.114671e-09 0.0009205367 1.242975e-07 2.426444e-12 1.727226e-07

In [29]:
rowSums(ace_mystates_hmm$states) # probabilities of all states add up to 1.00 :)

  [1] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 [38] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 [75] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
[112] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
[149] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
[186] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
[223] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
[260] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
[297] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
[334] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
[371] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1

In [31]:
# figure out which state is the most probable for all the internal nodes
apply(ace_mystates_hmm$states, MARGIN = 1, FUN = which.max) # MARGIN = 1 means apply the function to each row

  [1] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 [38] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 5 5 1 1 1 1 1 1 1 1
 [75] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 1 1 1 1 1 1 1
[112] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 4
[149] 4 4 4 4 4 4 4 4 4 4 4 4 4 4 1 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
[186] 4 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 4
[223] 4 4 4 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
[260] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 3 3 1 1 1 1 1 1 1 1 1 1 1 1 1 1
[297] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
[334] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 4 4 4 4 4 4 4 4 4 4
[371] 4 4 4 4 4 4 4 4 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 6

In [38]:
PHYLOGENY # our phylogeny has 395 tips ans 394 internal nodes and we reconstructed ancestral traits for the internal nodes

Phylogenetic tree with 395 tips and 394 internal nodes.

Tip labels:
  Anaphalis_aureopunctata, Anaphalis_hancockii, Solidago_decurrens, Doellingeria_scabra, Aster_tataricus, Artemisia_igniaria, ...
Node labels:
  , Spermatophyta, Mesangiospermae, mrcaott2ott121, eudicotyledons, mrcaott2ott969, ...

Rooted; includes branch length(s).

In [39]:
dim(ace_mystates_hmm$states) # got 394 rows and 6 columns

[1] 394   6

In [50]:
# based on the legend of the corHMM model output
STATES_LEGEND <- c("AM", "AMEcM", "AMNM", "EcM", "ErM", "NM")
STATES_LEGEND

[1] "AM"    "AMEcM" "AMNM"  "EcM"   "ErM"   "NM"

[1] "AMNM"  "AM"    "ErM"   "NM"    "AMEcM" "EcM"

In [52]:
# reconstructed ancestral states of the internal nodes, with node numbers as names
STATES_LEGEND[apply(ace_mystates_hmm$states, MARGIN = 1, FUN = which.max)]

  [1] "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"
 [10] "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"
 [19] "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"
 [28] "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"
 [37] "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"
 [46] "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"
 [55] "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"
 [64] "AM"    "ErM"   "ErM"   "AM"    "AM"    "AM"    "AM"    "AM"    "AM"
 [73] "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"
 [82] "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"
 [91] "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"
[100] "AM"    "AM"    "AM"    "AMEcM" "AMEcM" "AM"    "AM"    "AM"    "AM"
[109] "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"
[118] "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"
[127] "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"
[136] "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"
[145] "AM"    "AM"    "AM"    "EcM"   "EcM"   "EcM"   "EcM"   "EcM"   "EcM"
[154] "EcM"   "EcM"   "EcM"   "EcM"   "EcM"   "EcM"   "EcM"   "EcM"   "EcM"
[163] "AM"    "EcM"   "EcM"   "EcM"   "EcM"   "EcM"   "EcM"   "EcM"   "EcM"
[172] "EcM"   "EcM"   "EcM"   "EcM"   "EcM"   "EcM"   "EcM"   "EcM"   "EcM"
[181] "EcM"   "EcM"   "EcM"   "EcM"   "EcM"   "EcM"   "AM"    "AM"    "AM"
[190] "AM"    "AM"    "AM"    "AM"    "AM"    "AMEcM" "AMEcM" "AMEcM" "AMEcM"
[199] "AMEcM" "AMEcM" "AMEcM" "AMEcM" "AMEcM" "AMEcM" "AMEcM" "AM"    "AM"
[208] "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"
[217] "AM"    "AM"    "AM"    "AM"    "AM"    "EcM"   "EcM"   "EcM"   "EcM"
[226] "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"
[235] "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"
[244] "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"
[253] "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"
[262] "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"
[271] "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"
[280] "AM"    "AMNM"  "AMNM"  "AM"    "AM"    "AM"    "AM"    "AM"    "AM"
[289] "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"
[298] "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"
[307] "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"
[316] "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"
[325] "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"
[334] "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"
[343] "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"
[352] "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"
[361] "EcM"   "EcM"   "EcM"   "EcM"   "EcM"   "EcM"   "EcM"   "EcM"   "EcM"
[370] "EcM"   "EcM"   "EcM"   "EcM"   "EcM"   "EcM"   "EcM"   "EcM"   "EcM"
[379] "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "AM"
[388] "AM"    "AM"    "AM"    "AM"    "AM"    "AM"    "NM"

In [ ]:


# WHAT WE NEED HERE IS A DICTIONARY OF WHICH NODES DESCEND FROM WHICH NODES, SO WE CAN LOOK UP THE STATE TRANSITIONS AND CONTINUOUS TRAIT CHANGES
# http://www.phytools.org/eqg/Exercise_3.2/
# By convention, the tips of the tree are numbered 1 through n for n tips; and the nodes are numbered n + 1 through n + m for m nodes
# the matrix edge contains the beginning and ending node number for all the nodes and tips in the tree.
PHYLOGENY$edge

phyedges <- as.data.frame(PHYLOGENY$edge)
colnames(phyedges) <- c("from", "to")

for (i in 1:nrow(phyedges)) {
    print(ace_srl_fastanc[as.character(phyedges[i, ][, "from"])]) # - ace_srl_fastanc[phyedges[i, ][, "to"]])
}