# ___Phylogenetic traversal of ACEs___
---------------------------------------------------

In [1]:
print(R.version$version.string)

[1] "R version 4.5.2 (2025-10-31 ucrt)"

In [2]:
suppressPackageStartupMessages({
    library("ape")
    library("phytools")
    library("corHMM")
    library("diversitree")
})

set.seed(2026-1-26)

In [3]:
STATES <- read.csv("../../data/chapter2/FREDv3subset/finalized_states_395_species.csv", stringsAsFactors = TRUE)[, c("binominal", "state")] # finalized mycorrhizal states
COLLAB_AXIS <- read.csv("../../data/chapter2/FREDv3subset/collab_ord1_species_avgs_SRL_RD.csv", stringsAsFactors = TRUE) # first order species averaged RD and SRL values
MERGED <- merge(x = STATES, y = COLLAB_AXIS, by = "binominal") # merge the two datasets into one, based on the binominal names
stopifnot(nrow(MERGED)==395)

PHYLOGENY <- ape::multi2di(ape::read.tree("../../data/chapter2/uphylomaker/FRED_subset_collab_395sp.tre")) # phylogenetic tree created for the 395 species using U.PhyloMaker
stopifnot(length(PHYLOGENY$tip.label)==395)

# MERGED contains spaces in the binominal names - replace that with underscores; and '/' in mycorrhizal states that need to be removed
data <- data.frame(binominal = gsub(MERGED$binominal, pattern = ' ', replacement = '_'), RD = MERGED$F00679, SRL = MERGED$F00727, myco = gsub(x = MERGED$state, pattern = '/', replacement = ''))
matched_row_indices <- match(PHYLOGENY$tip.label, data$binominal)
stopifnot(all(data$binominal[matched_row_indices] == PHYLOGENY$tip.label))
data <- data[matched_row_indices, ] # reorder the dataset to match the species order in the phylogeny
stopifnot(all(data$binominal == PHYLOGENY$tip.label))
stopifnot(length(unique(data$binominal)) == length(data$binominal))

In [4]:
# FOR CONVENIRNCE
RD <- setNames(object = data$RD, nm = data$binominal)
SRL <- setNames(object = data$SRL, nm = data$binominal)
STATES <- setNames(object = data$myco, nm = data$binominal)

In [5]:
table(STATES) # welp

STATES
   AM AMEcM  AMNM   EcM   ErM    NM
  300    15     8    65     3     4

# PLOT THE PHYLOGENY AND NODE & TIP NUMBERS, IT'LL HELP IN TRACING DOWN CHANGES AND SHIFTS IN TRAITS

par(mar=c(0, 0, 0, 0))
png(filename = "../../plots/FRED_subset_collab_395sp_nodes_n_tips.png", width = 18000, height = 18000, units = "px", res = 300)
phytools::plotTree(tree = PHYLOGENY, ftype = "i", fsize = 1.2, type = "fan", lwd = 1, offset = 4)
# with interactive left to default, got a warning for every label
phytools::labelnodes(text = 1:(PHYLOGENY$Nnode + length(PHYLOGENY$tip.label)), node = 1:(PHYLOGENY$Nnode + length(PHYLOGENY$tip.label)), cex = 1, interactive = FALSE)
dev.off()

### ___ACE of discrete categorical traits using `ape`, `corHMM`, `phytools` & `diversitree`___
------------------------------------------------------

In [5]:
ape::is.ultrametric(PHYLOGENY) # diversitree requires the phylogeny to be ultrametric

[1] TRUE

In [6]:
# diversitree::make.mkn requires the states to be encodes as numbers
STATES_TO_NUMERIC <- setNames(seq_along(unique(STATES)), unique(STATES)) # numeric encoding of the discrete character states
STATES_NUMERIC <- setNames(unname(STATES_TO_NUMERIC[unname(STATES)]), names(STATES)) # named vector for states with numeric encodings

In [7]:
# diversitree::make.mk2() can only be used with binary state discrete characters
fnlikelihood <- diversitree::make.mkn(tree = PHYLOGENY, states = STATES_NUMERIC, k = length(unique(STATES)))

In [8]:
fnlikelihood

Mk(n) likelihood function:
  * Parameter vector takes 30 elements:
     - q12, q13, q14, q15, q16, q21, q23, q24, q25, q26, q31, q32, q34,
       q35, q36, q41, q42, q43, q45, q46, q51, q52, q53, q54, q56, q61,
       q62, q63, q64, q65
  * Function takes arguments (with defaults)
     - pars: Parameter vector
     - root [ROOT.OBS]: Type of root treatment
     - root.p [NULL]: Vector of root state probabilities
     - intermediates [FALSE]: Also return intermediate values?
  * Phylogeny with 395 tips and 394 nodes
     - Taxa: Anaphalis_aureopunctata, Anaphalis_hancockii, ...
  * References:
     - Pagel (1994)
     - Lewis (2001)
R definition:
function (pars, root = ROOT.OBS, root.p = NULL, intermediates = FALSE)

In [40]:
# pars argument of the likelihood function
# for make.mkn, a vector of k(k-1) parameters, in the order q12,q13,...q1k, q21,q23,...,q2k,...qk(k-1),
# corresponding to the off-diagonal elements of the Q matrix in row order. The order of parameters can be seen by running argnames(f)

# in our case k is 6, so we need (6x(6-1)) 30 values???

In [10]:
tm <- Sys.time()
# this is an ARD model
dtmod <- diversitree::find.mle(func = fnlikelihood, x.init = rep(x = 1, times = 30), # x.init and any extra args will get passed to the likelihood function
                      root = diversitree::ROOT.FLAT)
# needs a bit more work to run properly :(
tm <- Sys.time() - tm

Warning message in mle.search(func2, x.init, control, lower, upper):
"Convergence problems in find.mle (subplex): number of function evaluations exceeds 'maxit'"

In [6]:
#----------------------------------------------------------------------------------------------------------------------------------------------------------
# choosing the ARD model for mycorrhizal state evolution as it has been demonstrated that different transitions happen at different rates
# and some transitions are prectically irreversible compared to others
#----------------------------------------------------------------------------------------------------------------------------------------------------------

tm <- Sys.time()

# there are multiple ways to do ACE of discrete characters 
# ace_mystates_rr <- phytools::rerootingMethod(tree = PHYLOGENY, x = STATES, model = "ARD") - phytools::rerootingMethod method should not be used with non-symmetrical rate models of evolution
# read more here - https://blog.phytools.org/2023/06/decommissioning-rerootingmethod-and.html
ace_mystates_hmm <- corHMM::corHMM(phy = PHYLOGENY, data = data[, c("binominal", "myco")], model = "ARD", node.states = "marginal", rate.cat = 1)
ace_mystates_ape <- ape::ace(phy = PHYLOGENY, x = STATES, type = "discrete", method = "ML", model = "ARD", marginal = FALSE) # ape::ace used a non traditional way to compute marginal ACEs, see its documentation for more details
# setting marginal = FALSE actually returns the marginal ACEs, see the documentation of ape::ace for more details
ace_mystates_ancr <- phytools::ancr(phytools::fitMk(tree = PHYLOGENY, x = STATES, model = "ARD"))

tm <- Sys.time() - tm

# ace_mystates_dvt <- diversitree::asr.marginal()

You specified 'fixed.nodes=FALSE' but included a phy object with node labels. These node labels have been removed.

Warning message in corHMM::corHMM(phy = PHYLOGENY, data = data[, c("binominal", :
"Branch lengths of 0 detected. Adding 1e-5 to these branches."

State distribution in data:
States:	1	2	3	4	5	6
Counts:	300	15	8	65	3	4
Beginning thorough optimization search -- performing 0 random restarts
Finished. Inferring ancestral states using marginal reconstruction.

Warning message in sqrt(diag(solve(h))):
"NaNs produced"

In [7]:
tm

Time difference of 12.70665 mins

In [8]:
save(ace_mystates_hmm, ace_mystates_ape, ace_mystates_ancr, file = "../rdata/statesARD.RData")

In [59]:
ace_mystates_ape$lik.anc # ACEs from ape::ace

                   AM           AMEcM        AMNM         EcM
                   0.1780089    0.1676518788 0.1678401104 1.578816e-01
Spermatophyta      0.6310923    0.0084811117 0.0046860970 3.366761e-01
Mesangiospermae    0.9977983    0.0008959747 0.0007030378 4.115483e-05
mrcaott2ott121     0.9976928    0.0009168643 0.0008248789 5.344119e-06
eudicotyledons     0.9955824    0.0018530047 0.0015131992 1.288869e-04
mrcaott2ott969     0.9940670    0.0023076272 0.0023267179 7.443955e-05
Pentapetalae       0.9924739    0.0039979010 0.0019058349 5.098264e-05
mrcaott248ott19688 0.9834832    0.0065906228 0.0053868733 6.934968e-04
mrcaott248ott557   0.9799111    0.0082624305 0.0065630318 3.467028e-04
mrcaott248ott27233 0.9797556    0.0108912152 0.0042882178 4.049869e-04
mrcaott248ott650   0.9774911    0.0117853692 0.0054856190 2.174150e-04
mrcaott248ott320   0.9757427    0.0123543061 0.0042993860 1.789938e-03
campanulids        0.9673735    0.0145043475 0.0055300586 4.354440e-03
mrcaott320ott1673  0.9670032    0.0110497531 0.0039363376 1.047386e-02
                   0.9899060    0.0029321117 0.0019047774 2.115764e-03
                   0.9881637    0.0055348484 0.0028746640 3.499209e-04
                   0.9843578    0.0075760994 0.0035912460 6.109644e-04
                   0.9816607    0.0081978836 0.0031675447 2.314347e-03
                   0.8086079    0.0168679193 0.1465737446 2.002443e-04
                   0.9798027    0.0102673418 0.0040901042 7.688703e-04
                   0.9966889    0.0016731319 0.0009606002 4.263214e-06
                   0.9965312    0.0016880241 0.0011374858 2.134477e-07
                   0.9994221    0.0002588024 0.0002538513 7.811364e-09
                   0.9994209    0.0002587232 0.0002553313 2.040185e-10
                   0.9995146    0.0002009126 0.0002268013 7.251092e-09
                   0.9995146    0.0002009126 0.0002268013 7.251092e-09
mrcaott1673ott2128 0.9661098    0.0109185195 0.0038878062 1.182774e-02
                   0.9526553    0.0044630855 0.0027037722 3.370560e-02
                   0.9895208    0.0030718166 0.0019303927 2.146189e-03
                   0.9885059    0.0057224691 0.0024715783 3.932248e-04
⋮                  ⋮            ⋮            ⋮            ⋮
                   1.952400e-06 3.703915e-03 1.373258e-03 9.775860e-01
                   5.950434e-06 5.821818e-03 2.067447e-03 9.720363e-01
                   1.788712e-06 7.121708e-03 2.580946e-03 9.697772e-01
                   6.305267e-08 4.062671e-03 2.035501e-03 9.829753e-01
                   8.628467e-07 7.744318e-03 3.126837e-03 9.623560e-01
                   7.746716e-07 8.962482e-03 4.402356e-03 9.510712e-01
                   2.572344e-05 9.388769e-03 3.050990e-03 9.582853e-01
                   1.934132e-06 5.784774e-03 2.082286e-03 9.758888e-01
                   4.824249e-08 4.448854e-03 2.321011e-03 9.771865e-01
                   3.732906e-08 4.272236e-03 2.652649e-03 9.753601e-01
                   1.461767e-06 1.946789e-03 1.044126e-03 9.873188e-01
                   5.631226e-08 2.283654e-03 1.378036e-03 9.829639e-01
                   3.557412e-12 2.817704e-05 1.758832e-05 9.998826e-01
                   5.492356e-07 1.160760e-03 6.828667e-04 9.930566e-01
                   5.893573e-01 8.472562e-03 4.897637e-03 3.774475e-01
                   7.091522e-01 7.982216e-03 4.429964e-03 2.616004e-01
                   7.444630e-01 7.523753e-03 4.256912e-03 2.283067e-01
                   7.046422e-01 1.149511e-02 6.671445e-03 2.534363e-01
                   8.539510e-01 1.393533e-02 5.449827e-03 1.096627e-01
                   8.725718e-01 8.939484e-03 4.152566e-03 1.016949e-01
                   8.849891e-01 7.961212e-03 4.609388e-03 8.848971e-02
                   5.287769e-01 2.067592e-02 1.295760e-02 3.938916e-01
                   9.319003e-01 1.337409e-02 4.909850e-03 3.812913e-02
                   9.810773e-01 4.199700e-03 2.400612e-03 7.229412e-03
                   9.860552e-01 5.010184e-03 2.326563e-03 2.864414e-03
                   9.843833e-01 6.603714e-03 2.663197e-03 2.479721e-03
                   9.966635e-01 1.434279e-03 9.050508e-04 2.978402e-05
                   9.966635e-01 1.434279e-03 9.050508e-04 2.978402e-05
                   9.299637e-01 4.503584e-03 2.863192e-03 5.550879e-02
                   4.248050e-01 8.534802e-03 5.298187e-03 5.388290e-01
                   ErM          NM
                   1.634363e-01 1.651812e-01
Spermatophyta      1.046941e-02 8.594939e-03
Mesangiospermae    1.866265e-04 3.749249e-04
mrcaott2ott121     1.821930e-04 3.778822e-04
eudicotyledons     3.336534e-04 5.888886e-04
mrcaott2ott969     4.406896e-04 7.835524e-04
Pentapetalae       5.261451e-04 1.045281e-03
mrcaott248ott19688 1.511159e-03 2.334679e-03
mrcaott248ott557   1.854204e-03 3.062496e-03
mrcaott248ott27233 1.664066e-03 2.995946e-03
mrcaott248ott650   1.743825e-03 3.276681e-03
mrcaott248ott320   2.334228e-03 3.479459e-03
campanulids        3.532055e-03 4.705581e-03
mrcaott320ott1673  3.427214e-03 4.109653e-03
                   1.341661e-03 1.799708e-03
                   1.149820e-03 1.927028e-03
                   1.486859e-03 2.377077e-03
                   1.978408e-03 2.681166e-03
                   1.060392e-02 1.714626e-02
                   2.008455e-03 3.062486e-03
                   1.663504e-04 5.067789e-04
                   1.462481e-04 4.968019e-04
                   5.026729e-06 6.024742e-05
                   4.944906e-06 6.014186e-05
                   5.216019e-06 5.248532e-05
                   5.216019e-06 5.248532e-05
mrcaott1673ott2128 3.310672e-03 3.945456e-03
                   3.165319e-03 3.306942e-03
                   1.444361e-03 1.886446e-03
                   1.132108e-03 1.774693e-03
⋮                  ⋮            ⋮
                   0.0111108741 6.223990e-03
                   0.0122175919 7.850913e-03
                   0.0121733042 8.345087e-03
                   0.0061696890 4.756822e-03
                   0.0161878817 1.058410e-02
                   0.0214889201 1.407427e-02
                   0.0178059451 1.144328e-02
                   0.0096680949 6.574092e-03
                   0.0095096186 6.533962e-03
                   0.0104982373 7.216725e-03
                   0.0059552978 3.733548e-03
                   0.0082140021 5.160349e-03
                   0.0000386008 3.298574e-05
                   0.0030021994 2.096981e-03
                   0.0109994506 8.825577e-03
                   0.0091066273 7.728605e-03
                   0.0083082699 7.141393e-03
                   0.0126777623 1.107721e-02
                   0.0085505911 8.450624e-03
                   0.0064377341 6.203507e-03
                   0.0071304990 6.820096e-03
                   0.0233932100 2.030475e-02
                   0.0055898799 6.096737e-03
                   0.0023169801 2.776042e-03
                   0.0016389772 2.104643e-03
                   0.0016737532 2.196340e-03
                   0.0003394957 6.278988e-04
                   0.0003394957 6.278988e-04
                   0.0036076837 3.553009e-03
                   0.0128654410 9.667565e-03

In [9]:
ace_mystates_ancr$ace # ACEs from phytools::ancr

    AM           AMEcM        AMNM         EcM          ErM NM
396 0.0922244    5.397558e-05 4.223003e-01 6.549021e-04 0   4.847664e-01
397 0.5235107    7.513800e-05 2.002798e-01 6.545492e-04 0   2.754798e-01
398 0.9998722    3.853322e-14 7.447998e-05 1.675982e-08 0   5.331681e-05
399 0.9998850    1.748693e-12 6.994310e-05 6.788944e-09 0   4.503764e-05
400 0.9997399    1.083204e-11 2.386851e-04 2.615169e-08 0   2.134789e-05
401 0.9998144    1.764122e-10 1.683307e-04 6.426645e-08 0   1.716133e-05
402 0.9999619    1.840187e-13 2.902678e-05 4.559135e-09 0   9.086524e-06
403 0.9992811    1.071614e-10 5.613456e-04 5.538077e-08 0   1.574814e-04
404 0.9994928    1.314541e-09 3.961422e-04 2.140568e-07 0   1.108851e-04
405 0.9999542    2.030403e-11 3.640801e-05 4.438356e-08 0   9.361716e-06
406 0.9999813    2.972127e-11 1.597680e-05 3.453929e-08 0   2.667186e-06
407 0.9999138    1.030435e-10 8.209071e-05 9.793686e-08 0   4.023952e-06
408 0.9998391    8.036771e-09 1.466374e-04 8.288422e-07 0   1.338200e-05
409 0.9998001    4.623231e-09 1.778592e-04 9.334077e-07 0   2.105929e-05
410 0.9997272    2.894943e-09 2.329556e-04 2.149788e-06 0   3.770482e-05
411 0.9998761    1.561420e-10 1.138930e-04 1.602744e-07 0   9.811073e-06
412 0.9998015    4.959306e-10 1.924462e-04 1.866384e-07 0   5.880897e-06
413 0.9986445    1.466894e-10 1.348365e-03 1.413360e-07 0   6.985008e-06
414 0.8898402    9.107004e-14 1.101323e-01 5.081240e-09 0   2.747557e-05
415 0.9996289    5.761058e-10 3.618781e-04 2.091952e-07 0   9.047821e-06
416 0.9999990    6.546289e-14 8.846236e-07 4.119197e-09 0   9.847844e-08
417 0.9999995    2.997456e-13 4.246210e-07 1.398892e-09 0   4.682619e-08
418 1.0000000    1.325756e-17 2.421430e-08 5.660812e-11 0   3.020825e-09
419 1.0000000    1.586069e-16 1.968921e-08 2.385386e-11 0   2.467324e-09
420 1.0000000    1.506939e-17 3.577171e-08 5.355066e-11 0   5.937253e-09
421 1.0000000    1.506939e-17 3.577171e-08 5.355066e-11 0   5.937253e-09
422 0.9997455    3.866301e-09 2.253443e-04 7.967784e-07 0   2.835501e-05
423 0.9988230    2.360474e-07 1.015446e-03 1.220011e-05 0   1.491320e-04
424 0.9998292    2.042631e-09 1.432389e-04 1.350382e-06 0   2.620618e-05
425 0.9999659    1.905993e-10 2.935724e-05 1.661369e-07 0   4.625154e-06
⋮   ⋮            ⋮            ⋮            ⋮            ⋮   ⋮
760 3.682910e-10 2.682659e-06 6.569752e-17 9.999973e-01 0   7.912305e-18
761 1.360162e-08 5.216172e-08 8.825406e-15 9.999999e-01 0   9.727559e-16
762 5.861118e-09 4.224070e-09 1.674046e-15 1.000000e+00 0   1.763409e-16
763 4.880600e-10 1.798485e-10 1.208172e-17 1.000000e+00 0   1.233718e-18
764 2.499994e-09 2.074842e-09 3.052937e-16 1.000000e+00 0   3.132273e-17
765 2.902903e-09 6.560534e-10 4.078063e-16 1.000000e+00 0   4.067335e-17
766 4.948859e-08 2.573949e-07 1.093514e-13 9.999997e-01 0   1.166731e-14
767 5.405350e-09 6.425959e-09 1.422368e-15 1.000000e+00 0   1.533953e-16
768 2.684848e-10 1.080103e-10 3.643711e-18 1.000000e+00 0   3.660838e-19
769 3.251665e-10 2.870570e-11 5.304241e-18 1.000000e+00 0   5.233803e-19
770 6.692199e-09 5.459315e-07 2.085116e-15 9.999994e-01 0   2.801015e-16
771 8.826455e-10 7.935709e-08 3.938891e-17 9.999999e-01 0   3.942224e-18
772 3.225414e-12 2.935790e-12 5.365485e-22 1.000000e+00 0   5.547431e-23
773 1.643502e-08 2.825628e-06 9.988715e-15 9.999972e-01 0   1.675707e-15
774 8.737290e-02 9.472790e-07 3.652515e-01 4.619655e-05 0   5.473284e-01
775 1.621706e-01 1.998508e-06 2.438727e-01 3.257205e-05 0   5.939221e-01
776 1.790648e-01 5.809772e-07 1.697822e-01 1.549181e-05 0   6.511370e-01
777 1.512603e-01 1.402983e-08 1.060723e-01 1.741578e-06 0   7.426656e-01
778 2.187828e-01 1.953148e-08 8.562782e-02 1.188871e-06 0   6.955882e-01
779 2.611869e-01 5.524928e-08 7.021958e-02 2.276797e-06 0   6.685911e-01
780 2.914664e-01 4.244046e-09 5.271344e-02 8.043182e-07 0   6.558194e-01
781 2.040873e-01 2.948573e-09 4.865648e-02 7.938398e-07 0   7.472554e-01
782 6.127565e-01 3.832760e-08 3.135789e-02 1.935158e-06 0   3.558837e-01
783 9.748769e-01 6.162517e-09 2.665968e-03 1.841371e-06 0   2.245524e-02
784 9.967912e-01 1.328710e-09 4.086769e-04 5.598406e-07 0   2.799581e-03
785 9.991933e-01 2.905487e-09 1.596791e-04 6.686859e-07 0   6.463560e-04
786 9.999708e-01 1.337978e-13 6.016868e-06 4.878769e-09 0   2.315340e-05
787 9.999708e-01 1.337978e-13 6.016868e-06 4.878769e-09 0   2.315340e-05
788 9.039472e-01 2.250073e-06 2.456969e-02 8.357218e-05 0   7.139729e-02
789 6.135154e-02 9.654629e-07 4.340563e-01 1.627552e-05 0   5.045749e-01

In [11]:
ace_mystates_hmm$states # ACEs from corHMM

      (1,R1)       (2,R1)       (3,R1)       (4,R1)       (5,R1)
 [1,] 0.7384633    1.040288e-04 9.949760e-02 6.260653e-03 6.030534e-04
 [2,] 0.8501157    7.903288e-04 7.470484e-02 5.612279e-03 2.847190e-05
 [3,] 0.9991916    9.818027e-13 8.082208e-04 7.337873e-08 1.788241e-15
 [4,] 0.9992163    2.685532e-11 7.836026e-04 3.027913e-08 2.436969e-14
 [5,] 0.9989217    2.534694e-10 1.078005e-03 5.338445e-08 3.126602e-12
 [6,] 0.9990869    3.113141e-09 9.128237e-04 1.242300e-07 2.405557e-12
 [7,] 0.9995788    3.012160e-12 4.211973e-04 8.369504e-09 7.965788e-15
 [8,] 0.9973595    1.671280e-09 2.638908e-03 9.831632e-08 1.065142e-09
 [9,] 0.9979293    1.450902e-08 2.069273e-03 3.650733e-07 5.633531e-11
[10,] 0.9993963    3.182802e-10 6.035254e-04 8.145866e-08 1.258612e-13
[11,] 0.9995702    4.531248e-10 4.296910e-04 6.112759e-08 2.210562e-13
[12,] 0.9990360    1.879698e-09 9.636598e-04 1.864753e-07 7.482806e-12
[13,] 0.9987322    9.233462e-08 1.265237e-03 1.454447e-06 1.826678e-10
[14,] 0.9983811    6.125312e-08 1.615568e-03 1.750743e-06 1.038413e-10
[15,] 0.9977881    3.121577e-08 2.204256e-03 4.758945e-06 2.984081e-11
[16,] 0.9981537    2.446165e-09 1.845404e-03 3.710848e-07 2.961722e-12
[17,] 0.9974960    6.838834e-09 2.502978e-03 3.363073e-07 2.143665e-11
[18,] 0.9921029    2.029234e-09 7.895082e-03 2.470031e-07 3.927138e-11
[19,] 0.7823929    1.264219e-12 2.176054e-01 8.823196e-09 4.708660e-13
[20,] 0.9967057    8.025674e-09 3.293348e-03 3.671316e-07 1.204662e-12
[21,] 0.9999828    1.044486e-12 1.723567e-05 7.985729e-09 4.653676e-18
[22,] 0.9999892    4.642142e-12 1.079954e-05 2.646016e-09 5.973410e-17
[23,] 0.9999993    4.091481e-16 6.810006e-07 1.262152e-10 7.884119e-22
[24,] 0.9999994    2.667464e-15 6.240524e-07 6.260351e-11 5.151919e-21
[25,] 0.9999991    7.616473e-16 8.632460e-07 1.613028e-10 1.257189e-23
[26,] 0.9999991    7.678645e-16 8.631238e-07 1.610112e-10 2.606013e-23
[27,] 0.9980203    6.144983e-08 1.975870e-03 1.576401e-06 1.467844e-10
[28,] 0.9954394    2.382559e-06 4.509998e-03 2.401447e-05 3.674261e-09
[29,] 0.9989645    2.487355e-08 1.031931e-03 2.876967e-06 5.010663e-12
[30,] 0.9996694    2.737584e-09 3.302663e-04 3.229358e-07 2.380538e-13
[31,] ⋮            ⋮            ⋮            ⋮            ⋮
[32,] 3.736972e-10 2.483034e-04 1.350875e-15 9.997517e-01 5.450464e-28
[33,] 1.368160e-08 9.067603e-06 8.708033e-14 9.999909e-01 1.370198e-22
[34,] 5.755719e-09 4.076288e-07 1.670722e-14 9.999996e-01 3.193920e-23
[35,] 4.566405e-10 6.670798e-09 1.224686e-16 1.000000e+00 1.263420e-24
[36,] 2.482954e-09 5.264790e-07 3.111639e-15 9.999995e-01 1.005157e-23
[37,] 2.920201e-09 1.317562e-07 4.163435e-15 9.999999e-01 4.890963e-24
[38,] 5.427876e-08 4.354061e-05 1.079748e-12 9.999564e-01 1.417391e-21
[39,] 5.276238e-09 9.907913e-07 1.404337e-14 9.999990e-01 3.996264e-23
[40,] 2.541588e-10 2.259793e-08 3.727926e-17 1.000000e+00 4.411977e-25
[41,] 3.121922e-10 4.474645e-09 5.463542e-17 1.000000e+00 1.715905e-25
[42,] 6.453063e-09 2.217643e-05 1.851143e-14 9.999778e-01 1.751464e-22
[43,] 8.621597e-10 6.608954e-06 4.076650e-16 9.999934e-01 6.283215e-25
[44,] 2.932963e-12 3.452558e-10 5.467029e-21 1.000000e+00 1.054376e-26
[45,] 1.240121e-08 3.421254e-05 5.876155e-14 9.999658e-01 5.249309e-22
[46,] 5.807723e-01 2.927962e-05 1.447573e-01 7.360603e-04 4.526584e-04
[47,] 6.914252e-01 6.269638e-05 1.164856e-01 4.721254e-04 4.356089e-05
[48,] 7.227800e-01 2.022098e-05 1.314991e-01 1.956632e-04 8.437661e-06
[49,] 6.440665e-01 5.938827e-07 2.321584e-01 1.879161e-05 7.350247e-06
[50,] 7.185324e-01 8.598442e-07 2.145347e-01 1.037514e-05 2.736050e-07
[51,] 7.704157e-01 1.737569e-06 1.896837e-01 1.426786e-05 7.318710e-08
[52,] 7.946430e-01 1.663396e-07 1.859090e-01 4.967948e-06 6.723420e-08
[53,] 4.712702e-01 4.642231e-08 4.260064e-01 3.096329e-06 4.216226e-06
[54,] 8.775315e-01 7.952820e-07 1.162442e-01 7.133888e-06 2.370861e-09
[55,] 9.866739e-01 8.746918e-08 1.324826e-02 4.515471e-06 4.021945e-11
[56,] 9.965991e-01 1.876860e-08 3.396489e-03 1.113090e-06 6.300525e-12
[57,] 9.984138e-01 3.876132e-08 1.584159e-03 1.222172e-06 9.268900e-12
[58,] 9.998927e-01 6.384474e-12 1.073162e-04 1.466567e-08 6.718212e-18
[59,] 9.998927e-01 6.387175e-12 1.073155e-04 1.466468e-08 6.862802e-18
[60,] 9.532298e-01 1.968533e-05 3.988070e-02 2.953713e-04 9.735318e-08
[61,] 2.028134e-01 2.007483e-05 1.545373e-01 2.009900e-04 3.404947e-03
      (6,R1)
 [1,] 1.550713e-01
 [2,] 6.874840e-02
 [3,] 1.214591e-07
 [4,] 8.614221e-08
 [5,] 2.003021e-07
 [6,] 1.708078e-07
 [7,] 9.662081e-09
 [8,] 1.522477e-06
 [9,] 1.053377e-06
[10,] 5.588549e-08
[11,] 2.386121e-08
[12,] 1.972251e-07
[13,] 9.857984e-07
[14,] 1.491213e-06
[15,] 2.822205e-06
[16,] 5.255201e-07
[17,] 6.312421e-07
[18,] 1.755629e-06
[19,] 1.669460e-06
[20,] 5.719970e-07
[21,] 5.977666e-11
[22,] 1.324300e-11
[23,] 4.777725e-14
[24,] 2.622359e-14
[25,] 6.695250e-14
[26,] 6.686600e-14
[27,] 2.150294e-06
[28,] 2.420771e-05
[29,] 6.969337e-07
[30,] 3.715396e-08
[31,] ⋮
[32,] 1.329690e-21
[33,] 3.954005e-19
[34,] 3.342805e-20
[35,] 2.516894e-23
[36,] 2.892801e-21
[37,] 4.697287e-21
[38,] 1.657701e-17
[39,] 2.680912e-20
[40,] 6.139940e-24
[41,] 1.342715e-23
[42,] 6.090650e-20
[43,] 2.181032e-22
[44,] 2.479085e-27
[45,] 2.663905e-19
[46,] 2.732525e-01
[47,] 1.915108e-01
[48,] 1.454965e-01
[49,] 1.237483e-01
[50,] 6.692148e-02
[51,] 3.988458e-02
[52,] 1.944273e-02
[53,] 1.027160e-01
[54,] 6.216405e-03
[55,] 7.321165e-05
[56,] 3.235943e-06
[57,] 7.981251e-07
[58,] 1.358207e-09
[59,] 1.358137e-09
[60,] 6.574351e-03
[61,] 6.390234e-01

In [12]:
# the output of corHMM lacks explicit column names
# outputs of ape and corHMM lack explicit row names (in node numbers)

In [33]:
# colnames(ace_mystates_ape$lik.anc)
# MARGIN = 1 is used for row wise apply
state_preds_ape <- colnames(ace_mystates_ape$lik.anc)[apply(ace_mystates_ape$lik.anc, MARGIN = 1, FUN = which.max)]

In [34]:
ace_mystates_hmm

Fit
      -lnL      AIC     AICc Rate.cat ntax
 -127.3412 314.6825 319.7924        1  395

Legend
      1       2       3       4       5       6
   "AM" "AMEcM"  "AMNM"   "EcM"   "ErM"    "NM"

Rates
            (1,R1)       (2,R1)       (3,R1)      (4,R1)       (5,R1)
(1,R1)          NA 0.0003220296 0.0009737899 0.000201527 6.729156e-05
(2,R1) 0.000000001           NA 0.0000000010 0.017445718 1.000000e-09
(3,R1) 0.016863141 0.0000000010           NA 0.000000001 1.000000e-09
(4,R1) 0.001299564 0.0000000010 0.0000000010          NA 1.000000e-09
(5,R1) 0.000000001 0.0000000010 0.0000000010 0.000000001           NA
(6,R1) 0.000000001 0.0000000010 0.0071694536 0.000000001 1.000000e-09
             (6,R1)
(1,R1) 1.000000e-09
(2,R1) 1.000000e-09
(3,R1) 1.027515e-02
(4,R1) 1.000039e-09
(5,R1) 9.735390e-04
(6,R1)           NA

Arrived at a reliable solution

In [35]:
# based on the legend of the corHMM model output
STATES_LEGEND_CORHMM <- c("AM", "AMEcM", "AMNM", "EcM", "ErM", "NM")
STATES_LEGEND_CORHMM

[1] "AM"    "AMEcM" "AMNM"  "EcM"   "ErM"   "NM"

In [36]:
state_preds_hmm <- STATES_LEGEND_CORHMM[apply(ace_mystates_hmm$states, MARGIN = 1, FUN = which.max)]

In [37]:
# colnames(ace_mystates_ancr$ace)
# only the output of phytools::ancr has explicit node numbers as row names!!
state_preds_phy <- colnames(ace_mystates_ancr$ace)[apply(ace_mystates_ancr$ace, MARGIN = 1, FUN = which.max)]

In [39]:
mean(state_preds_ape == state_preds_hmm)

[1] 0.9720812

In [40]:
mean(state_preds_ape == state_preds_phy) # the lowest

[1] 0.9492386

In [41]:
mean(state_preds_phy == state_preds_hmm) # the highest

[1] 0.9771574

In [44]:
# let's stick to the reconstructions of corHMM
internode_states <- setNames(state_preds_hmm, nm = rownames(ace_mystates_ancr$ace))

In [53]:
all(rownames(ace_mystates_ancr$ace) == 396:789)

[1] TRUE

In [75]:
stopifnot(all(PHYLOGENY$tip.label == names(STATES)))
all_states <- c(setNames(unname(STATES), nm = as.character(1:395)), # tips
                                    internode_states) # internodes
stopifnot(length(all_states) == PHYLOGENY$Nnode + length(PHYLOGENY$tip.label))

In [ ]:
ace_mystates_dvt <- diversitree::

In [76]:
#--------------------------------
# ACE OF CONTINUOUS TRAITS
#--------------------------------

ace_srl_fastanc <- phytools::fastAnc(tree = PHYLOGENY, x = SRL) # this is a Maximim Likelihood (ML) based method - Brownian motion models which essentially is a Markov process on a continuous scale
# https://eeob-macroevolution.github.io/Practicals/Ancestral_State_Estimation/AncStateEstimation_Tutorial.html
# the link above provides detailed info on ACE, and also recommends incorporating fossil data when available to make the ACE more rigorous
# do we have fossil root trait data???????

# Liam J. Revell's website says that phytools::fastAnc also uses Felsenstein's re-rooting algorithm for ACE of continuous characters - http://www.phytools.org/Cordoba2017/ex/7/Anc-states-continuous.html
# PCMIR (page 224) recommends fitting phytools::fastAnc with vars=TRUE, CI=TRUE as ACE happens with lots of uncertainty, so it's important to know the CIs of each reconstruction

In [84]:
all_srl <- c(setNames(SRL, nm = as.character(1:395)), # tip SRL values
                      ace_srl_fastanc) # reconstructed SRL values
stopifnot(length(all_srl) == PHYLOGENY$Nnode + length(PHYLOGENY$tip.label))

In [92]:
nodedata <- data.frame(SRL = all_srl, STATE = all_states) # includes the extant and reconstructed clade trait data
head(nodedata)

  SRL      STATE
1 479.1550 AMNM
2 319.8579 AM
3 202.8837 AM
4 219.2008 AM
5 297.1100 AM
6 204.1529 AM

In [ ]:
# the plan here is to find out the (2) nodes at each branch of the phylogeny and capture and store the changes in SRL and mycorrhizal states
# corresponding to the branches
# we can start this with the internodes as the tips can only be at the descendent end of a branch, never at an ancestor end

In [91]:
head(PHYLOGENY$edge) # the edge attribute of the phylo object contains all the edge details, where each row corresponds to a branch in the phylogeny

     [,1] [,2]
[1,] 396  397
[2,] 397  398
[3,] 398  399
[4,] 399  400
[5,] 400  401
[6,] 401  402

In [123]:
nodedata[345, "SRL"] - nodedata[231, "SRL"]

[1] -65.70696

In [131]:
# figure out all the discrete state transitions included in our reconstruction

transitions <- list()
changes <- vector(length = nrow(PHYLOGENY$edge), mode = "double")

for (i in 1:nrow(PHYLOGENY$edge)) {
    # PHYLOGENY$edge[i, ] returns a tuple of node numbers defining a branch (from, to)
    from <- PHYLOGENY$edge[i, ][1]
    to <- PHYLOGENY$edge[i, ][1]

    # corresponding state transition
    transitions[[i]] <- c(nodedata[from, "STATE"], nodedata[to, "STATE"])

    # corresponding continuous trait change
    changes[i] <- (nodedata[from, "SRL"] - nodedata[to, "SRL"]) # SRL of ancestor - SRL of the descendent
    print(paste0(nodedata[from, "SRL"], ' ', nodedata[to, "SRL"])) # that's fucked up :/
}

[1] "87.1887153768475 87.1887153768475"
[1] "74.3876076639289 74.3876076639289"
[1] "86.4443514259488 86.4443514259488"
[1] "86.8177302379011 86.8177302379011"
[1] "90.6010055805565 90.6010055805565"
[1] "90.7782055189518 90.7782055189518"
[1] "94.5855739567672 94.5855739567672"
[1] "96.9510153424221 96.9510153424221"
[1] "98.664126564583 98.664126564583"
[1] "104.677020630068 104.677020630068"
[1] "107.671044067949 107.671044067949"
[1] "112.587736400722 112.587736400722"
[1] "115.830567394651 115.830567394651"
[1] "129.237740416893 129.237740416893"
[1] "222.481007356438 222.481007356438"
[1] "232.332123408069 232.332123408069"
[1] "247.855763416357 247.855763416357"
[1] "257.153239504369 257.153239504369"
[1] "394.527379966816 394.527379966816"
[1] "394.527379966816 394.527379966816"
[1] "257.153239504369 257.153239504369"
[1] "236.116948931954 236.116948931954"
[1] "240.248685710358 240.248685710358"
[1] "237.272275554028 237.272275554028"
[1] "237.272275554028 237.272275554028"
[1] "240.248685710358 240.248685710358"
[1] "236.116948931954 236.116948931954"
[1] "142.137414572242 142.137414572242"
[1] "142.137414572242 142.137414572242"
[1] "141.927114372127 141.927114372127"
[1] "141.927114372127 141.927114372127"
[1] "247.855763416357 247.855763416357"
[1] "232.332123408069 232.332123408069"
[1] "172.616555538644 172.616555538644"
[1] "172.616555538644 172.616555538644"
[1] "172.616555538644 172.616555538644"
[1] "172.616555538644 172.616555538644"
[1] "222.481007356438 222.481007356438"
[1] "129.237740416893 129.237740416893"
[1] "127.732250400023 127.732250400023"
[1] "132.495412758204 132.495412758204"
[1] "132.495412758204 132.495412758204"
[1] "127.863640394828 127.863640394828"
[1] "127.863640394828 127.863640394828"
[1] "119.630923384251 119.630923384251"
[1] "137.285504797173 137.285504797173"
[1] "137.285504797173 137.285504797173"
[1] "131.22701986033 131.22701986033"
[1] "131.22701986033 131.22701986033"
[1] "119.630923384251 119.630923384251"
[1] "127.732250400023 127.732250400023"
[1] "122.244585240337 122.244585240337"
[1] "112.831626587038 112.831626587038"
[1] "112.831626587038 112.831626587038"
[1] "122.244585240337 122.244585240337"
[1] "115.830567394651 115.830567394651"
[1] "112.587736400722 112.587736400722"
[1] "113.897791844328 113.897791844328"
[1] "113.095021839435 113.095021839435"
[1] "125.953736859888 125.953736859888"
[1] "162.668993983994 162.668993983994"
[1] "167.289120248732 167.289120248732"
[1] "215.224132833067 215.224132833067"
[1] "215.224132833067 215.224132833067"
[1] "222.979876461067 222.979876461067"
[1] "222.979876461067 222.979876461067"
[1] "167.289120248732 167.289120248732"
[1] "166.608697329057 166.608697329057"
[1] "163.057993946397 163.057993946397"
[1] "163.057993946397 163.057993946397"
[1] "166.608697329057 166.608697329057"
[1] "162.668993983994 162.668993983994"
[1] "125.953736859888 125.953736859888"
[1] "60.6166100761782 60.6166100761782"
[1] "50.8455890774765 50.8455890774765"
[1] "36.1585467343134 36.1585467343134"
[1] "35.4529214469513 35.4529214469513"
[1] "35.4529214469513 35.4529214469513"
[1] "36.1585467343134 36.1585467343134"
[1] "50.8455890774765 50.8455890774765"
[1] "52.0353150733727 52.0353150733727"
[1] "52.0353150733727 52.0353150733727"
[1] "51.9783034764804 51.9783034764804"
[1] "49.0431471449108 49.0431471449108"
[1] "49.0431471449108 49.0431471449108"
[1] "51.9783034764804 51.9783034764804"
[1] "60.6166100761782 60.6166100761782"
[1] "113.095021839435 113.095021839435"
[1] "113.897791844328 113.897791844328"
[1] "127.356486789039 127.356486789039"
[1] "164.38110006248 164.38110006248"
[1] "164.38110006248 164.38110006248"
[1] "148.875735814279 148.875735814279"
[1] "163.01681318316 163.01681318316"
[1] "163.01681318316 163.01681318316"
[1] "148.875735814279 148.875735814279"
[1] "164.38110006248 164.38110006248"
[1] "250.760425865083 250.760425865083"
[1] "119.705851005591 119.705851005591"
[1] "115.083952995352 115.083952995352"
[1] "132.247509699199 132.247509699199"
[1] "132.247509699199 132.247509699199"
[1] "115.083952995352 115.083952995352"
[1] "119.705851005591 119.705851005591"
[1] "250.760425865083 250.760425865083"
[1] "164.38110006248 164.38110006248"
[1] "127.356486789039 127.356486789039"
[1] "74.0112785186262 74.0112785186262"
[1] "74.0112785186262 74.0112785186262"
[1] "107.671044067949 107.671044067949"
[1] "113.573916074465 113.573916074465"
[1] "115.910341147723 115.910341147723"
[1] "120.666388729152 120.666388729152"
[1] "131.314283763069 131.314283763069"
[1] "301.37314143607 301.37314143607"
[1] "301.37314143607 301.37314143607"
[1] "435.6116282546 435.6116282546"
[1] "435.6116282546 435.6116282546"
[1] "131.314283763069 131.314283763069"
[1] "120.666388729152 120.666388729152"
[1] "77.4972699347946 77.4972699347946"
[1] "77.4972699347946 77.4972699347946"
[1] "72.1522331280433 72.1522331280433"
[1] "72.1522331280433 72.1522331280433"
[1] "115.910341147723 115.910341147723"
[1] "114.651007825603 114.651007825603"
[1] "100.308058422442 100.308058422442"
[1] "70.068735243953 70.068735243953"
[1] "70.8483650505078 70.8483650505078"
[1] "67.8407844117494 67.8407844117494"
[1] "67.8407844117494 67.8407844117494"
[1] "65.5685794492197 65.5685794492197"
[1] "65.5685794492197 65.5685794492197"
[1] "70.8483650505078 70.8483650505078"
[1] "70.068735243953 70.068735243953"
[1] "100.308058422442 100.308058422442"
[1] "78.273005001886 78.273005001886"
[1] "39.9527014998635 39.9527014998635"
[1] "39.9527014998635 39.9527014998635"
[1] "78.273005001886 78.273005001886"
[1] "114.651007825603 114.651007825603"
[1] "74.5639813272388 74.5639813272388"
[1] "108.724190469967 108.724190469967"
[1] "108.724190469967 108.724190469967"
[1] "74.5639813272388 74.5639813272388"
[1] "113.573916074465 113.573916074465"
[1] "112.83658670128 112.83658670128"
[1] "112.83658670128 112.83658670128"
[1] "104.677020630068 104.677020630068"
[1] "101.15452425223 101.15452425223"
[1] "163.780487223951 163.780487223951"
[1] "184.605932247536 184.605932247536"
[1] "184.605932247536 184.605932247536"
[1] "163.780487223951 163.780487223951"
[1] "101.15452425223 101.15452425223"
[1] "94.6148211025554 94.6148211025554"
[1] "86.358384851764 86.358384851764"
[1] "54.6059007080994 54.6059007080994"
[1] "34.60671889857 34.60671889857"
[1] "34.4308042470949 34.4308042470949"
[1] "34.4308042470949 34.4308042470949"
[1] "34.60671889857 34.60671889857"
[1] "54.6059007080994 54.6059007080994"
[1] "53.5884880243133 53.5884880243133"
[1] "46.2920164533657 46.2920164533657"
[1] "46.2920164533657 46.2920164533657"
[1] "53.5884880243133 53.5884880243133"
[1] "86.358384851764 86.358384851764"
[1] "94.6148211025554 94.6148211025554"
[1] "13.8741814839408 13.8741814839408"
[1] "13.8741814839408 13.8741814839408"
[1] "98.664126564583 98.664126564583"
[1] "96.9510153424221 96.9510153424221"
[1] "94.5855739567672 94.5855739567672"
[1] "94.0153301455713 94.0153301455713"
[1] "94.2572297258177 94.2572297258177"
[1] "94.9214324244031 94.9214324244031"
[1] "95.5300272039988 95.5300272039988"
[1] "97.0919832108866 97.0919832108866"
[1] "68.463547557997 68.463547557997"
[1] "61.4422439663941 61.4422439663941"
[1] "60.6042097793249 60.6042097793249"
[1] "60.6042097793249 60.6042097793249"
[1] "67.2549424676895 67.2549424676895"
[1] "124.588383478943 124.588383478943"
[1] "124.588383478943 124.588383478943"
[1] "67.2549424676895 67.2549424676895"
[1] "61.4422439663941 61.4422439663941"
[1] "68.463547557997 68.463547557997"
[1] "62.2396911440952 62.2396911440952"
[1] "75.6160834218896 75.6160834218896"
[1] "93.1903237168277 93.1903237168277"
[1] "91.1484609822238 91.1484609822238"
[1] "91.1484609822238 91.1484609822238"
[1] "93.1903237168277 93.1903237168277"
[1] "75.6160834218896 75.6160834218896"
[1] "67.9199768952733 67.9199768952733"
[1] "67.9199768952733 67.9199768952733"
[1] "62.2396911440952 62.2396911440952"
[1] "97.0919832108866 97.0919832108866"
[1] "99.1585533966333 99.1585533966333"
[1] "126.290643648744 126.290643648744"
[1] "138.010224136137 138.010224136137"
[1] "138.010224136137 138.010224136137"
[1] "138.010224136137 138.010224136137"
[1] "149.770888244265 149.770888244265"
[1] "153.065629424601 153.065629424601"
[1] "148.78705210418 148.78705210418"
[1] "140.505183403079 140.505183403079"
[1] "140.505183403079 140.505183403079"
[1] "148.78705210418 148.78705210418"
[1] "133.723898438981 133.723898438981"
[1] "133.723898438981 133.723898438981"
[1] "153.065629424601 153.065629424601"
[1] "154.795192872611 154.795192872611"
[1] "154.795192872611 154.795192872611"
[1] "203.496107435514 203.496107435514"
[1] "245.37235789999 245.37235789999"
[1] "245.37235789999 245.37235789999"
[1] "203.496107435514 203.496107435514"
[1] "149.770888244265 149.770888244265"
[1] "138.010224136137 138.010224136137"
[1] "143.331996525752 143.331996525752"
[1] "143.420115262198 143.420115262198"
[1] "80.7512038139684 80.7512038139684"
[1] "81.0727158070188 81.0727158070188"
[1] "68.2294411618422 68.2294411618422"
[1] "68.2294411618422 68.2294411618422"
[1] "81.0727158070188 81.0727158070188"
[1] "80.7512038139684 80.7512038139684"
[1] "79.1726815238815 79.1726815238815"
[1] "116.038582884208 116.038582884208"
[1] "116.038582884208 116.038582884208"
[1] "97.2205074718803 97.2205074718803"
[1] "97.2205074718803 97.2205074718803"
[1] "79.1726815238815 79.1726815238815"
[1] "79.053435452464 79.053435452464"
[1] "73.906125045566 73.906125045566"
[1] "73.906125045566 73.906125045566"
[1] "87.3200018184083 87.3200018184083"
[1] "87.3200018184083 87.3200018184083"
[1] "79.053435452464 79.053435452464"
[1] "75.7111329458967 75.7111329458967"
[1] "75.7111329458967 75.7111329458967"
[1] "143.420115262198 143.420115262198"
[1] "213.773985492221 213.773985492221"
[1] "213.773985492221 213.773985492221"
[1] "143.331996525752 143.331996525752"
[1] "144.258447717786 144.258447717786"
[1] "144.258447717786 144.258447717786"
[1] "144.451394756593 144.451394756593"
[1] "111.725645154387 111.725645154387"
[1] "90.9279242666054 90.9279242666054"
[1] "84.3692019330806 84.3692019330806"
[1] "84.3692019330806 84.3692019330806"
[1] "90.9279242666054 90.9279242666054"
[1] "111.725645154387 111.725645154387"
[1] "111.740566502962 111.740566502962"
[1] "111.740566502962 111.740566502962"
[1] "144.451394756593 144.451394756593"
[1] "126.290643648744 126.290643648744"
[1] "120.408866210251 120.408866210251"
[1] "113.185308823364 113.185308823364"
[1] "107.756431946706 107.756431946706"
[1] "105.245138660455 105.245138660455"
[1] "96.2923444910826 96.2923444910826"
[1] "96.2923444910826 96.2923444910826"
[1] "105.245138660455 105.245138660455"
[1] "107.756431946706 107.756431946706"
[1] "105.556642738853 105.556642738853"
[1] "105.556642738853 105.556642738853"
[1] "113.185308823364 113.185308823364"
[1] "99.3451023434282 99.3451023434282"
[1] "99.3451023434282 99.3451023434282"
[1] "94.399268709065 94.399268709065"
[1] "94.399268709065 94.399268709065"
[1] "111.532297577382 111.532297577382"
[1] "111.532297577382 111.532297577382"
[1] "99.3451023434282 99.3451023434282"
[1] "99.3451023434282 99.3451023434282"
[1] "120.408866210251 120.408866210251"
[1] "99.1585533966333 99.1585533966333"
[1] "97.295459647606 97.295459647606"
[1] "97.295459647606 97.295459647606"
[1] "94.0406727808537 94.0406727808537"
[1] "92.8456134988191 92.8456134988191"
[1] "90.856883279838 90.856883279838"
[1] "87.9307715166001 87.9307715166001"
[1] "80.1557414412778 80.1557414412778"
[1] "57.5188464964373 57.5188464964373"
[1] "57.5188464964373 57.5188464964373"
[1] "80.1557414412778 80.1557414412778"
[1] "95.785958206536 95.785958206536"
[1] "95.785958206536 95.785958206536"
[1] "87.9307715166001 87.9307715166001"
[1] "75.0873446329238 75.0873446329238"
[1] "75.0873446329238 75.0873446329238"
[1] "75.0873446329238 75.0873446329238"
[1] "75.0873446329238 75.0873446329238"
[1] "82.328037507309 82.328037507309"
[1] "81.3275822620488 81.3275822620488"
[1] "81.3275822620488 81.3275822620488"
[1] "82.328037507309 82.328037507309"
[1] "90.856883279838 90.856883279838"
[1] "112.897277254487 112.897277254487"
[1] "112.897277254487 112.897277254487"
[1] "125.444268964442 125.444268964442"
[1] "125.444268964442 125.444268964442"
[1] "92.8456134988191 92.8456134988191"
[1] "88.4556315540362 88.4556315540362"
[1] "84.3205526134176 84.3205526134176"
[1] "72.6277971597168 72.6277971597168"
[1] "72.6277971597168 72.6277971597168"
[1] "84.3205526134176 84.3205526134176"
[1] "88.4556315540362 88.4556315540362"
[1] "94.0406727808537 94.0406727808537"
[1] "86.7992493948495 86.7992493948495"
[1] "78.6180483401011 78.6180483401011"
[1] "79.6698943914405 79.6698943914405"
[1] "79.6698943914405 79.6698943914405"
[1] "79.6698943914405 79.6698943914405"
[1] "79.6698943914405 79.6698943914405"
[1] "79.6698943914405 79.6698943914405"
[1] "79.6698943914405 79.6698943914405"
[1] "79.6698943914405 79.6698943914405"
[1] "79.6698943914405 79.6698943914405"
[1] "82.0312412012715 82.0312412012715"
[1] "82.8454373587352 82.8454373587352"
[1] "83.777608637006 83.777608637006"
[1] "83.777608637006 83.777608637006"
[1] "82.8454373587352 82.8454373587352"
[1] "82.0312412012715 82.0312412012715"
[1] "104.137253065369 104.137253065369"
[1] "104.137253065369 104.137253065369"
[1] "79.6698943914405 79.6698943914405"
[1] "79.6698943914405 79.6698943914405"
[1] "79.6698943914405 79.6698943914405"
[1] "79.6698943914405 79.6698943914405"
[1] "78.6180483401011 78.6180483401011"
[1] "73.3279803347432 73.3279803347432"
[1] "74.5380734921755 74.5380734921755"
[1] "74.9729895693805 74.9729895693805"
[1] "74.9729895693805 74.9729895693805"
[1] "89.8245419485538 89.8245419485538"
[1] "89.822234529065 89.822234529065"
[1] "89.5342977409058 89.5342977409058"
[1] "89.5342977409058 89.5342977409058"
[1] "95.4636659552475 95.4636659552475"
[1] "95.4636659552475 95.4636659552475"
[1] "89.822234529065 89.822234529065"
[1] "89.8245419485538 89.8245419485538"
[1] "95.5587052929101 95.5587052929101"
[1] "95.5587052929101 95.5587052929101"
[1] "74.9729895693805 74.9729895693805"
[1] "74.9729895693805 74.9729895693805"
[1] "74.5380734921755 74.5380734921755"
[1] "73.3279803347432 73.3279803347432"
[1] "65.4681385531919 65.4681385531919"
[1] "65.4681385531919 65.4681385531919"
[1] "49.7842037157546 49.7842037157546"
[1] "49.7842037157546 49.7842037157546"
[1] "86.7992493948495 86.7992493948495"
[1] "95.5300272039988 95.5300272039988"
[1] "94.4437809082628 94.4437809082628"
[1] "94.1204050452547 94.1204050452547"
[1] "91.2382043089363 91.2382043089363"
[1] "88.2690514721609 88.2690514721609"
[1] "88.2752579303937 88.2752579303937"
[1] "85.1103501440849 85.1103501440849"
[1] "85.1103501440849 85.1103501440849"
[1] "89.0559191168721 89.0559191168721"
[1] "89.0559191168721 89.0559191168721"
[1] "88.2752579303937 88.2752579303937"
[1] "88.6173324322326 88.6173324322326"
[1] "179.500058161405 179.500058161405"
[1] "231.2185717853 231.2185717853"
[1] "231.2185717853 231.2185717853"
[1] "248.077731588953 248.077731588953"
[1] "201.345556306756 201.345556306756"
[1] "201.345556306756 201.345556306756"
[1] "214.535586549199 214.535586549199"
[1] "214.535586549199 214.535586549199"
[1] "248.077731588953 248.077731588953"
[1] "179.500058161405 179.500058161405"
[1] "177.125793879516 177.125793879516"
[1] "177.125793879516 177.125793879516"
[1] "177.125793879516 177.125793879516"
[1] "177.125793879516 177.125793879516"
[1] "169.031299631286 169.031299631286"
[1] "170.037061703847 170.037061703847"
[1] "183.101327358796 183.101327358796"
[1] "183.101327358796 183.101327358796"
[1] "170.037061703847 170.037061703847"
[1] "169.031299631286 169.031299631286"
[1] "177.125793879516 177.125793879516"
[1] "177.125793879516 177.125793879516"
[1] "88.6173324322326 88.6173324322326"
[1] "88.2690514721609 88.2690514721609"
[1] "86.9352181400703 86.9352181400703"
[1] "50.5666200367555 50.5666200367555"
[1] "50.5666200367555 50.5666200367555"
[1] "47.3923728959086 47.3923728959086"
[1] "47.3923728959086 47.3923728959086"
[1] "86.9352181400703 86.9352181400703"
[1] "91.2382043089363 91.2382043089363"
[1] "93.6388053021036 93.6388053021036"
[1] "93.6388053021036 93.6388053021036"
[1] "122.226845541131 122.226845541131"
[1] "108.621117126457 108.621117126457"
[1] "108.621117126457 108.621117126457"
[1] "122.226845541131 122.226845541131"
[1] "182.386148508664 182.386148508664"
[1] "182.386148508664 182.386148508664"
[1] "94.1204050452547 94.1204050452547"
[1] "72.9476932966375 72.9476932966375"
[1] "72.9476932966375 72.9476932966375"
[1] "82.0663509218166 82.0663509218166"
[1] "82.0663509218166 82.0663509218166"
[1] "94.4437809082628 94.4437809082628"
[1] "105.148578358293 105.148578358293"
[1] "144.021381335363 144.021381335363"
[1] "144.021381335363 144.021381335363"
[1] "105.148578358293 105.148578358293"
[1] "94.9214324244031 94.9214324244031"
[1] "94.964743259814 94.964743259814"
[1] "90.8564882864381 90.8564882864381"
[1] "91.0245752523958 91.0245752523958"
[1] "81.5608431304553 81.5608431304553"
[1] "73.8417748017209 73.8417748017209"
[1] "85.7319133096748 85.7319133096748"
[1] "85.7319133096748 85.7319133096748"
[1] "101.521713505835 101.521713505835"
[1] "101.390842350223 101.390842350223"
[1] "101.390842350223 101.390842350223"
[1] "101.521713505835 101.521713505835"
[1] "85.7319133096748 85.7319133096748"
[1] "85.7319133096748 85.7319133096748"
[1] "73.8417748017209 73.8417748017209"
[1] "81.5608431304553 81.5608431304553"
[1] "93.1651198823427 93.1651198823427"
[1] "93.1651198823427 93.1651198823427"
[1] "91.0245752523958 91.0245752523958"
[1] "90.8564882864381 90.8564882864381"
[1] "82.9426021303378 82.9426021303378"
[1] "82.5620567328719 82.5620567328719"
[1] "81.7468846205474 81.7468846205474"
[1] "76.5360741341814 76.5360741341814"
[1] "76.322951207843 76.322951207843"
[1] "76.322951207843 76.322951207843"
[1] "76.5360741341814 76.5360741341814"
[1] "81.7468846205474 81.7468846205474"
[1] "89.0251413524629 89.0251413524629"
[1] "89.0251413524629 89.0251413524629"
[1] "82.5620567328719 82.5620567328719"
[1] "73.6839040623588 73.6839040623588"
[1] "73.6839040623588 73.6839040623588"
[1] "73.6839040623588 73.6839040623588"
[1] "74.8050822237882 74.8050822237882"
[1] "74.8050822237882 74.8050822237882"
[1] "73.6839040623588 73.6839040623588"
[1] "66.6410286465661 66.6410286465661"
[1] "75.8553002939391 75.8553002939391"
[1] "75.8553002939391 75.8553002939391"
[1] "79.2955395793512 79.2955395793512"
[1] "85.3358411866565 85.3358411866565"
[1] "87.086773983448 87.086773983448"
[1] "92.1611793176618 92.1611793176618"
[1] "92.1396224624395 92.1396224624395"
[1] "95.9712365432709 95.9712365432709"
[1] "95.9712365432709 95.9712365432709"
[1] "92.1396224624395 92.1396224624395"
[1] "92.1611793176618 92.1611793176618"
[1] "87.086773983448 87.086773983448"
[1] "86.1147117191716 86.1147117191716"
[1] "85.8875112560956 85.8875112560956"
[1] "84.562008360621 84.562008360621"
[1] "84.562008360621 84.562008360621"
[1] "85.8875112560956 85.8875112560956"
[1] "86.1147117191716 86.1147117191716"
[1] "74.0924854479442 74.0924854479442"
[1] "74.0924854479442 74.0924854479442"
[1] "85.3358411866565 85.3358411866565"
[1] "86.5610540026008 86.5610540026008"
[1] "88.2840965043452 88.2840965043452"
[1] "88.2840965043452 88.2840965043452"
[1] "100.410367849476 100.410367849476"
[1] "100.410367849476 100.410367849476"
[1] "86.5610540026008 86.5610540026008"
[1] "79.2955395793512 79.2955395793512"
[1] "75.8553002939391 75.8553002939391"
[1] "75.8553002939391 75.8553002939391"
[1] "66.6410286465661 66.6410286465661"
[1] "34.9584266808531 34.9584266808531"
[1] "34.9584266808531 34.9584266808531"
[1] "82.9426021303378 82.9426021303378"
[1] "87.738451235511 87.738451235511"
[1] "87.738451235511 87.738451235511"
[1] "86.4835695068984 86.4835695068984"
[1] "86.4835695068984 86.4835695068984"
[1] "94.964743259814 94.964743259814"
[1] "103.617610127397 103.617610127397"
[1] "141.336414623999 141.336414623999"
[1] "218.453105304024 218.453105304024"

In [127]:
changes

  [1] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 [38] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 [75] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
[112] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
[149] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
[186] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
[223] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
[260] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
[297] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
[334] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
[371] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
[408] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
[445] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
[482] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
[519] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
[556] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
[593] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
[630] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
[667] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
[704] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
[741] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
[778] 0 0 0 0 0 0 0 0 0 0 0